/**
 * Generate random names based on specified settings.
 *
 * @param {Object} settings - The settings for generating names.
 * @param {string} [settings.starts_with='any'] - Starting letter or letters of the first name.
 * @param {string} [settings.ends_with='any'] - Ending letter or letters of the first name.
 * @param {boolean} [settings.generate_last_name=true] - Whether to generate last names.
 * @param {string} [settings.gender='any'] - Gender of the generated names ('male', 'female', or 'any').
 * @param {string} [settings.country='any'] - Country for name generation ('denmark', 'usa', 'germany', or 'any').
 * @param {number} [settings.count=3] - Number of names to generate.
 * @param {number} [settings.names_with_title=50] - Percentage of names to include a title with.
 * @param {string} [settings.title='Mr'] - Title to include with names.
 * @returns {string[]} - An array of generated names.
 */
export function generateName(settings) {
  const defaultSettings = {
    starts_with: 'any',
    ends_with: 'any',
    generate_last_name: true,
    gender: 'any',
    country: 'any',
    count: 1,
    names_with_title: 0,
    title: 'Mr.',
  };

  const mergedSettings = { ...defaultSettings, ...settings };

  const {
    starts_with,
    ends_with,
    gender,
    count,
    names_with_title,
    title,
    country, // New: Get the country setting
  } = mergedSettings;

  function getRandomElement(array) {
    return array[Math.floor(Math.random() * array.length)];
  }

  function filterNames(namesArray, startsWith, endsWith) {
    return namesArray.filter((name) => {
      const firstName = name.split(' ')[0];

      const firstNameValid =
        (startsWith === 'any' || firstName.startsWith(startsWith)) &&
        (endsWith === 'any' || firstName.endsWith(endsWith));

      return firstNameValid;
    });
  }

  const names = {
    us: {
      male: ["Alex", "Michael", "Ethan", "Jack", "Liam", "Daniel", "Matthew", "Christopher", "Andrew", "Joseph", "William", "David", "Benjamin", "Ryan", "James", "John", "Nicholas", "Jonathan", "Jacob", "Tyler", "Elijah", "Nathan", "Brandon", "Samuel", "Dylan", "Zachary", "Logan", "Caleb", "Mason", "Evan", "Luke", "Adam", "Isaac", "Aiden", "Jackson", "Gavin", "Michael", "Carter", "Henry", "Owen", "Wyatt", "Jayden", "Cameron", "Connor", "Landon", "Christian", "Hunter", "Isaiah", "Oliver", "Lucas", "Eli", "Aaron", "Charles", "David", "Parker", "Evan", "Aiden", "Leo", "Jordan", "Seth", "Cole", "Oscar", "Adrian", "Derek", "Max", "Peter", "Jake", "Colton", "Bryce", "Tristan", "Alexandre", "Victor", "Jaden", "Joel", "Trevor", "Brendan", "Gage", "Carson", "Dawson", "Kyle", "Colin", "Miles", "Jason", "Brody", "Asher", "Brian", "Brayden", "Caden", "Paul", "Ezra", "Kai", "Drew", "Griffin"],
      female: ["Emily", "Sophia", "Grace", "Olivia", "Emma", "Ava", "Mia", "Isabella", "Zoe", "Lily", "Chloe", "Charlotte", "Lillian", "Amelia", "Harper", "Evelyn", "Abigail", "Avery", "Sofia", "Ella", "Madison", "Scarlett", "Victoria", "Aria", "Grace", "Hannah", "Natalie", "Addison", "Lila", "Brooklyn", "Layla", "Audrey", "Zoey", "Penelope", "Mila", "Riley", "Leah", "Allison", "Aubrey", "Gabriella", "Kaylee", "Ariana", "Stella", "Bella", "Claire", "Skylar", "Samantha", "Nora", "Camila", "Aaliyah", "Ellie", "Lily", "Madelyn", "Arianna", "Taylor", "Lucy", "Scarlet", "Maya", "Elena", "Hailey", "Hazel", "Aurora", "Nevaeh", "Autumn", "Peyton", "Mackenzie", "Serenity", "Sadie", "Piper", "Trinity", "Amanda", "Kylie", "Eva", "Caroline", "Arielle", "Jasmine", "Melanie", "Layla", "Alexandra", "Gianna", "Bailey", "Angelina", "Ruby", "Natalia", "Maria", "Lydia", "Paige", "Molly", "Katherine", "Faith", "Brianna", "Isabel", "Olive", "Eleanor"],
      last_names: ["Smith", "Johnson", "Williams", "Jones", "Brown", "Taylor", "Clark", "Evans", "Baker", "Ward", "Anderson", "Davis", "Martinez", "Jackson", "Harris", "Hill", "Young", "King", "Wright", "Lee", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Edwards", "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant", "Alexander", "Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford", "Hamilton"]
    },
  
    portugal: {
      male: ["Diogo", "Mateus", "Gonçalo", "João", "Miguel", "Rafael", "Tomás", "Rodrigo", "Francisco", "Martim", "Pedro", "André", "Tiago", "Lucas", "Gabriel", "Guilherme", "David", "Daniel", "Simão", "Alexandre", "António", "Ricardo", "Luís", "Hugo", "Vasco", "Filipe", "Bruno", "José", "Manuel", "Rui", "Nuno", "Leandro", "Ivan", "Carlos", "Ângelo", "Dinis", "Leonardo", "Alex", "Fábio", "Joaquim", "Nelson", "Fernando", "Eduardo", "Sérgio", "Hélder", "Jorge", "Marco", "Júlio", "Artur", "Felix", "Lorenzo", "Gil", "Salvador", "Renato", "Ricardo", "Javier", "Enzo", "Cristiano", "Mário", "Adriano", "Adrian", "Gustavo", "Álvaro", "Domingos", "Dylan", "Dário", "Henrique", "Israel", "Jaime", "Josué", "Kevin", "Lino", "Raul", "Salomão", "Santiago", "Sandro", "Urbano", "Valentim", "Valter", "Xavier", "Yuri", "Zé"],
      female: ["Inês", "Matilde", "Mariana", "Ana", "Joana", "Sofia", "Carolina", "Beatriz", "Margarida", "Rita", "Laura", "Diana", "Clara", "Leonor", "Marta", "Maria", "Gabriela", "Catarina", "Filipa", "Lara", "Helena", "Luísa", "Madalena", "Bianca", "Daniela", "Isabel", "Lúcia", "Eva", "Jéssica", "Teresa", "Carmo", "Alexandra", "Rafaela", "Andreia", "Sara", "Manuela", "Natália", "Fernanda", "Verónica", "Vera", "Ingrid", "Olga", "Paula", "Flor", "Irene", "Dora", "Cândida", "Estela", "Eunice", "Heloísa", "Gilda", "Iara", "Jaqueline", "Liliana", "Neuza", "Otília", "Penélope", "Quitéria", "Rosa", "Solange", "Tânia", "Ursula", "Vânia", "Wanda", "Xana", "Yara", "Zara", "Cláudia", "Irma", "Julieta", "Kelly", "Leticia", "Nádia", "Ondina", "Perpétua", "Rosalina", "Selma", "Tatiana", "Uma", "Violeta", "Wendy", "Xénia", "Yolanda", "Zuleide"],
      last_names: ["Silva", "Santos", "Pereira", "Oliveira", "Ferreira", "Costa", "Rodrigues", "Martins", "Jesus", "Nunes", "Gomes", "Lopes", "Marques", "Almeida", "Dias", "Cruz", "Mendes", "Moreira", "Rocha", "Sousa", "Fernandes", "Carvalho", "Teixeira", "Gonçalves", "Ribeiro", "Araújo", "Barbosa", "Leal", "Ramos", "Correia", "Cardoso", "Pinto", "Monteiro", "Morais", "Barros", "Melo", "Cavalcante", "Fonseca", "Mota", "Couto", "Henriques", "Campos", "Castro", "Lima", "Vieira", "Freitas", "Antunes", "Vargas", "Dantas", "Neves", "Azevedo", "Abreu", "Pires", "Simões", "Magalhães", "Vicente", "Figueiredo", "Freire", "Correia", "Madeira", "Aguiar", "Brito", "Serra", "Paiva", "Paixão", "Prado", "Soares", "Amorim", "Baptista", "Caldeira", "Cunha", "Farias", "Linhares", "Otero", "Quintana", "Rezende", "Tavares", "Uchoa", "Valladares", "Ximenes", "Zamora"]
    },
  
    sweden: {
      male: ["Erik", "Lukas", "Oscar", "Gustav", "Axel", "William", "Leo", "Adam", "Oliver", "Isak", "Emil", "Karl", "Felix", "Liam", "Nils", "Jakob", "Victor", "Anton", "Elias", "Noah", "Hugo", "Albin", "Viktor", "Charlie", "Elliot", "Edvin", "Benjamin", "Filip", "Rasmus", "Sebastian", "Theo", "Leon", "Max", "Samuel", "Eddie", "David", "Albert", "Jonathan", "Joel", "Simon", "Gustaf", "Daniel", "Alfred", "Malte", "Adrian", "Walter", "Melker", "Arvid", "Alex", "Isac", "Noel", "Julian", "Milo", "Linus", "Eduard", "Wilhelm", "Sigurd", "Henrik", "Johan", "Anders", "Axel", "Frederik", "Kristian", "Niklas", "Magnus", "Marcus", "Mikael", "Björn", "Christian", "Sebastian", "Lars", "Emil", "Oskar", "Jonas", "Vilhelm", "Ludvig", "Johannes", "Henning", "Theodor", "Fabian", "Alexander", "Artur", "Erik", "Elis", "Folke", "Olof", "Rolf", "Ruben", "Staffan", "Valter", "Yngve"],
      female: ["Elsa", "Maja", "Alice", "Astrid", "Olivia", "Julia", "Wilma", "Emma", "Ella", "Emilia", "Klara", "Ida", "Alma", "Linnéa", "Agnes", "Nora", "Isabella", "Hanna", "Elin", "Ebba", "Ellen", "Signe", "Nova", "Sara", "Selma", "Vera", "Stella", "Ester", "Matilda", "Iris", "Lovisa", "Amanda", "Elvira", "Tilde", "Linnea", "Saga", "Sophie", "Molly", "Frida", "Tilda", "Ingrid", "Joline", "Melissa", "Malin", "Nellie", "Clara", "Rebecca", "Josefin", "Moa", "Lova", "Elise", "Felicia", "Hedda", "Isabelle", "Liv", "Alicia", "Annie", "Ronja", "Märta", "Sofia", "Aurora", "Linda", "Isa", "Johanna", "Svea", "Olga", "Helena", "Tindra", "Hilda", "Miriam", "Rut", "Leah", "Greta", "Vilda", "Tove", "Tyra", "Ester", "Elsa", "Karla", "Vanja", "Alva", "Alina", "Ellinor", "Asta", "Hedvig"],
      last_names: ["Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson", "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson", "Jensen", "Håkansson", "Forsberg", "Danielsson", "Olofsson", "Lindgren", "Magnusson", "Isaksson", "Lindström", "Berg", "Haglund", "Sjöberg", "Lundberg", "Lindqvist", "Forsström", "Bergström", "Westin", "Wallin", "Hedström", "Löfgren", "Hedberg", "Petersson", "Nordström", "Lindholm", "Hermansson", "Falk", "Hansson", "Sundqvist", "Östberg", "Wikström", "Ekström", "Holm", "Lönn", "Werner", "Nyberg", "Sjögren", "Lööf", "Gunnarsson", "Strömberg", "Åberg", "Holmberg", "Eklund", "Lundin", "Edlund", "Strand", "Göransson", "Carlsson", "Vikström", "Åkesson", "Dahlberg", "Ahlgren", "Engström", "Björk", "Berglund", "Bergqvist", "Källström", "Sundberg", "Englund", "Ågren", "Söderberg", "Viklund", "Öberg", "Erlansson", "Jung", "Viklund", "Fridlund", "Molin", "Mårtensson"]
    },
  
    denmark: {
      male: ["Frederik", "Anders", "Mads", "Christian", "Nikolaj", "Emil", "Mikkel", "Jens", "Lars", "Søren", "Thomas", "Henrik", "Rasmus", "Jesper", "Martin", "Peter", "Kasper", "Daniel", "Jørgen", "Ole", "Jørgen", "Ole", "Bent", "Erik", "Jannik", "Hans", "Svend", "Lasse", "Viktor", "Gustav", "Claus", "Kristian", "Jonas", "Casper", "Andreas", "Simon", "David", "Oliver", "Lukas", "Sebastian", "Marcus", "Mathias", "Karl", "Sigurd", "Anton", "Philip", "Albert", "Alexander", "Jonathan", "Alfred", "Elias", "Viggo", "Magnus", "Victor", "Oscar", "Arthur", "Theo", "Malthe", "Johannes", "August", "Valdemar", "Felix", "Benjamin", "Axel", "Noah", "Elias", "Adam", "Lucas", "Gabriel", "Isaac", "Aksel", "Emanuel", "Hugo", "Elis", "Elliot", "Bastian", "Vincent", "Filip", "Ferdinand", "Carl", "Patrick", "Nicolai", "Robert", "Michael", "Henning", "Morten", "Stefan", "Rene"],
      female: ["Emma", "Sofie", "Freja", "Ida", "Mathilde", "Anna", "Clara", "Laura", "Isabella", "Emilie", "Karla", "Maja", "Ella", "Lærke", "Josefine", "Nina", "Maria", "Louise", "Luna", "Nanna", "Olivia", "Malou", "Amalie", "Astrid", "Alberte", "Cecilie", "Julie", "Camilla", "Sara", "Signe", "Katrine", "Helene", "Caroline", "Marie", "Sophie", "Johanne", "Rikke", "Ditte", "Julia", "Viktoria", "Agnes", "Emilia", "Alma", "Anja", "Hannah", "Alma", "Victoria", "Frida", "Selma", "Silje", "Asta", "Hedvig", "Mathea", "Eva", "Amira", "Sofia", "Tilde", "Amanda", "Thilde", "Lea", "Sille", "Anna", "Liva", "Ellen", "Thea", "Stine", "Rosa", "Lily", "Liva", "Nora", "Tilda", "Liv", "Aya", "Filippa", "Esther", "Ellinor", "Mille", "Lola", "Nicoline", "Ellie", "Liv", "Aya", "Vilma"],
      last_names: ["Hansen", "Jensen", "Andersen", "Christensen", "Nielsen", "Pedersen", "Madsen", "Kristensen", "Olsen", "Thomsen", "Larsen", "Rasmussen", "Sørensen", "Andreasen", "Petersen", "Mortensen", "Møller", "Mikkelsen", "Simonsen", "Knudsen", "Laursen", "Jørgensen", "Schmidt", "Eriksen", "Christiansen", "Damgaard", "Vestergaard", "Toft", "Lund", "Hermansen", "Kjeldsen", "Holm", "Jakobsen", "Vinter", "Svendsen", "Hoffmann", "Nielsen", "Fischer", "Nissen", "Lassen", "Jepsen", "Schou", "Lund", "Vang", "Bisgaard", "Torp", "Henriksen", "Jessen", "Frederiksen", "Hansen", "Jensen", "Andersen", "Christensen", "Nielsen", "Pedersen", "Madsen", "Kristensen", "Olsen", "Thomsen", "Larsen", "Rasmussen", "Sørensen", "Andreasen", "Petersen", "Mortensen", "Møller", "Mikkelsen", "Simonsen", "Knudsen", "Laursen", "Jørgensen", "Schmidt", "Eriksen", "Christiansen", "Damgaard", "Vestergaard", "Toft", "Lund", "Hermansen", "Kjeldsen", "Holm", "Jakobsen", "Vinter", "Svendsen", "Hoffmann", "Nielsen", "Fischer", "Nissen", "Lassen", "Jepsen", "Schou", "Lund", "Vang", "Bisgaard", "Torp", "Henriksen", "Jessen", "Frederiksen"]
    },
  
    italy: {
      male: ["Luca", "Alessandro", "Matteo", "Lorenzo", "Davide", "Giovanni", "Leonardo", "Riccardo", "Francesco", "Marco", "Antonio", "Federico", "Andrea", "Niccolò", "Giuseppe", "Stefano", "Alberto", "Michele", "Gabriele", "Simone", "Enrico", "Vittorio", "Tommaso", "Daniele", "Raffaele", "Filippo", "Emanuele", "Alessio", "Mario", "Giorgio", "Pietro", "Paolo", "Roberto", "Claudio", "Massimo", "Gianluca", "Angelo", "Gianmaria", "Fabio", "Salvatore", "Domenico", "Diego", "Cristian", "Valerio", "Alessandro", "Dario", "Giancarlo", "Luigi", "Bruno", "Sergio", "Renato", "Umberto", "Marcello", "Rocco", "Vincenzo", "Amedeo", "Giovanni", "Vito", "Piero", "Alfredo", "Nicolò", "Giacomo", "Luciano", "Maurizio", "Giuliano", "Davide", "Eugenio", "Loris", "Fabrizio", "Vincenzo", "Gianluigi", "Fernando", "Ivan", "Angelo", "Riccardo", "Mauro", "Gianfranco", "Alessandro", "Gianpiero", "Gabriel", "Salvatore", "Ruggero", "Cesare", "Giuseppe", "Lorenzo", "Gianni", "Roberto", "Oscar"],
      female: ["Sofia", "Aurora", "Giulia", "Martina", "Emma", "Alice", "Greta", "Ludovica", "Alessia", "Camilla", "Isabella", "Francesca", "Elisa", "Elena", "Laura", "Anna", "Lucia", "Beatrice", "Livia", "Sara", "Matilde", "Vittoria", "Arianna", "Valentina", "Eleonora", "Noemi", "Ginevra", "Bianca", "Stella", "Clara", "Serena", "Asia", "Margherita", "Rosalia", "Caterina", "Lara", "Federica", "Angelica", "Marta", "Virginia", "Gaia", "Rosa", "Simona", "Miriam", "Cinzia", "Nina", "Rachele", "Paola", "Silvia", "Viviana", "Nicole", "Carlotta", "Sonia", "Eva", "Michela", "Cristina", "Gloria", "Giovanna", "Emanuela", "Luisa", "Giusy", "Carmela", "Daniela", "Giada", "Ilaria", "Rita", "Maddalena", "Loredana", "Miranda", "Nadia", "Rosanna", "Fabiola", "Adele", "Lucrezia", "Filomena", "Gilda", "Teresa", "Vera", "Ornella", "Alessandra", "Matilda", "Amelia", "Lavinia", "Zita", "Erminia", "Giovanna", "Alda", "Enrica"],
      last_names: ["Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco", "Bruno", "Gallo", "Conti", "De Luca", "Mancini", "Costa", "Giordano", "Rizzo", "Lombardi", "Moretti", "Barbieri", "Fontana", "Santoro", "Mariani", "Rinaldi", "Caruso", "Ferrara", "Galli", "Martini", "Leone", "Longo", "Gentile", "Martino", "Serra", "Coppola", "Leoni", "Ferri", "Conte", "Fiorini", "De Rosa", "Pellegrini", "Gatti", "Guerriero", "Mazza", "Valentini", "Palmieri", "Bernardi", "Piras", "Marchetti", "Palumbo", "Monti", "Pellegrino", "Fiore", "Battaglia", "Cattaneo", "Amato", "Farina", "Bellini", "Lombardo", "Grasso", "Piazza", "Galli", "Carbone", "De Santis", "Romani", "Ruggeri", "Fabbri", "Cavallaro", "Milani", "Damico", "Rizzi", "De Angelis", "Palmisano", "Montanari", "Coppola", "De Filippo", "Liguori", "Brancaccio", "Nardi", "Amoroso", "Toscano", "Gigli", "Catalano", "Cerullo", "Vullo", "Lupo"]
    },
  
    france: {
      male: ["Louis", "Gabriel", "Jules", "Hugo", "Adam", "Paul", "Alexandre", "Maxime", "Arthur", "Nathan", "Léo", "Tom", "Ethan", "Théo", "Lucas", "Enzo", "Antoine", "Oscar", "Victor", "Gabin", "Mathis", "Léon", "Baptiste", "Noah", "Axel", "Matteo", "Raphaël", "Hector", "Valentin", "Marius", "Eliott", "Nolan", "Timéo", "Sacha", "Auguste", "Eden", "Côme", "Bastien", "Maël", "Evan", "Ilan", "Eli", "Émile", "Robin", "Gaspard", "Marceau", "Maxence", "Quentin", "Simon", "Alexis", "Tristan", "Alexandre", "André", "Benoît", "Cédric", "Denis", "Emmanuel", "Fabien", "Gérard", "Hervé", "Isaac", "Jacques", "Kilian", "Loïc", "Maurice", "Nicolas", "Olivier", "Pierre", "Quentin", "Romain", "Sébastien", "Thibault", "Ulric", "Vincent", "Walter", "Xavier", "Yves", "Zacharie", "Alain", "Bastien", "Camille", "Dorian", "Elliot", "Florian", "Guillaume", "Hugo"],
      female: ["Emma", "Chloé", "Léa", "Alice", "Manon", "Lola", "Camille", "Inès", "Lily", "Zoé", "Louise", "Jade", "Anna", "Rose", "Léna", "Mia", "Julia", "Agathe", "Eva", "Mila", "Sarah", "Clara", "Jeanne", "Ambre", "Lucie", "Maëlys", "Romane", "Mathilde", "Charlotte", "Gabrielle", "Louna", "Éva", "Nina", "Capucine", "Iris", "Ava", "Olivia", "Héloïse", "Eléonore", "Elsa", "Lison", "Zélie", "Léonie", "Apolline", "Roxane", "Constance", "Soline", "Éléna", "Noémie", "Lilou", "Lina", "Manon", "Laura", "Amandine", "Élodie", "Juliette", "Léane", "Axelle", "Maïwenn", "Anaïs", "Émilie", "Héloïse", "Sophie", "Aurélie", "Marie", "Claire", "Fleur", "Lise", "Colette", "Paule", "Diane", "Élise", "Joséphine", "Laure", "Irène", "Simone", "Marguerite", "Isabelle", "Océane", "Morgane", "Daphné", "Bérénice", "Thérèse", "Violette", "Prune", "Eulalie"],
      last_names: ["Martin", "Bernard", "Thomas", "Petit", "Robert", "Richard", "Durand", "Dubois", "Moreau", "Laurent", "Simon", "Michel", "Lefevre", "Leroy", "Roux", "David", "Bertrand", "Morel", "Fournier", "Girard", "Bonnet", "Dupont", "Lambert", "Fontaine", "Rousseau", "Vincent", "Muller", "Lefebvre", "Faure", "Andre", "Mercier", "Blanc", "Guerin", "Boyer", "Garnier", "Chevalier", "Francois", "Legrand", "Gauthier", "Garcia", "Perrin", "Robin", "Clement", "Morin", "Nicolas", "Henry", "Roussel", "Mathieu", "Guiot", "Dufour", "Brault", "Bourgeois", "Leclerc", "Gillet", "Colin", "Caron", "Marchand", "Leclercq", "Picard", "Lemoine", "Mallet", "Deschamps", "Poirier", "Rolland", "Leclerc", "Hubert", "Klein", "Jacquet", "Aubert", "Baron", "Collet", "Brun", "Da Silva", "Langlois", "Perez", "Guyot", "Martins", "Bouchet", "Charles", "Bailly", "Delaunay", "Le Gall", "Le Roux"]
    },
  
    germany: {
      male: ["Lukas", "Maximilian", "Paul", "Leon", "Felix", "Jonas", "Simon", "Tim", "Noah", "Philipp", "Julian", "Moritz", "Niklas", "Benjamin", "Matthias", "David", "Jan", "Luca", "Tom", "Jakob", "Anton", "Sebastian", "Johannes", "Fabian", "Oscar", "Jonathan", "Samuel", "Elias", "Vincent", "Alexander", "Daniel", "Hannes", "Liam", "Valentin", "Adrian", "Nico", "Erik", "Karl", "Marius", "Michael", "Leonard", "Christian", "Julius", "Finn", "Simon", "Emil", "Theo", "Raphael", "Markus", "Lennard", "Victor", "Nils", "Bastian", "Aaron", "Jannik", "Tobias", "Jannis", "Nikolai", "Fabio", "Malte", "Dominik", "Paul", "Matteo", "Joel", "Phil", "Yannick", "Marlon", "Till", "Luis", "Timon", "Lucas", "Janis", "Dennis", "Hendrik", "Nick", "Levi", "Clemens", "Ole", "Malik", "Jakob", "Lasse", "Carl", "Noel", "Gustav", "Jasper", "Timur", "Damian", "Enno", "Benedikt"],
      female: ["Lena", "Emma", "Mia", "Hannah", "Sophie", "Anna", "Marie", "Lina", "Laura", "Lea", "Emilia", "Amelie", "Elena", "Clara", "Johanna", "Isabella", "Julia", "Frieda", "Luisa", "Mila", "Charlotte", "Sophia", "Maja", "Nina", "Ella", "Leonie", "Emily", "Mathilda", "Zoe", "Alina", "Lara", "Sarah", "Victoria", "Lotta", "Jana", "Nele", "Luisa", "Paula", "Magdalena", "Jasmin", "Rosa", "Fiona", "Elisa", "Luise", "Marlene", "Antonia", "Amelia", "Lucia", "Ida", "Franziska", "Eva", "Helena", "Annelie", "Theresa", "Isabel", "Anastasia", "Jule", "Carolin", "Selina", "Liv", "Paulina", "Esther", "Helene", "Felicitas", "Marina", "Sofia", "Annika", "Leona", "Miriam", "Joana", "Stella", "Annalena", "Carlotta", "Rosalie", "Emelie", "Elina", "Josefine", "Elisabeth", "Melina", "Sina", "Alisa", "Mira", "Ronja", "Celine", "Liana", "Marit", "Chiara", "Viola", "Nadine"],
      last_names: ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann", "Schäfer", "Koch", "Bauer", "Richter", "Klein", "Schröder", "Neumann", "Schwarz", "Zimmermann", "Braun", "Krüger", "Hofmann", "Hartmann", "Lange", "Schmitt", "Werner", "Schmitz", "Krause", "Meier", "Lehmann", "Schmid", "Schulze", "Maier", "Köhler", "Herrmann", "König", "Walter", "Mayer", "Huber", "Kaiser", "Fuchs", "Peters", "Lang", "Scholz", "Möller", "Weiß", "Jung", "Hahn", "Vogel", "Schubert", "Frank", "Keller", "Wolf", "Schill", "Günther", "Roth", "Beck", "Lorenz", "Baumann", "Franke", "Albrecht", "Schuster", "Simon", "Ludwig", "Böhm", "Korn", "Kuhn", "Winter", "Kraus", "Beyer", "Otto", "Seidel", "Heinrich", "Brandt", "Sander", "Schreiber", "Eckert", "Götz", "Stein", "Ritter", "Kühn", "Arnold", "Vetter", "Bösch", "Schwarz", "Graf", "Friedrich", "Rudolph"]
    },
  
    china: {
      male: ["Wei", "Jian", "Ming", "Cheng", "Yong", "Xiao", "Bing", "Zhi", "Feng", "Jun", "Tao", "Lei", "Wei", "Hao", "Yi", "Xing", "Tian", "Rui", "Chao", "Kai", "Li", "Xuan", "Yu", "Shuai", "Zheng", "Dong", "Chen", "Shi", "Gang", "Hui", "Yan", "Peng", "Bin", "Zhang", "Yuan", "Han", "Zhong", "Qiang", "Xiang", "Ren", "Jia", "Zhu", "Bo", "Wen", "Jing", "Ru", "Hang", "Heng", "Xin", "Kun", "Guang", "Jin", "Xiang", "Lin", "Mao", "Hua", "Quan", "Meng", "Xue", "Zong", "Qing", "Chun", "Shan", "Liang", "Yun", "Huang", "Zhen", "Yong", "Zong", "Guo", "Chuan", "Hao", "Xian", "Chang", "Xun", "Zhong", "Cai", "Xiu", "Qiu", "Sheng", "Ling", "Wang", "Xue", "Yao", "Rong", "Long", "Teng", "Fang", "Kang", "Ran"],
      female: ["Mei", "Li", "Xin", "Hua", "Jing", "Yan", "Xia", "Qing", "Ying", "Yun", "Fang", "Xiu", "Xiang", "Ling", "Zhen", "Rui", "Xin", "Yuan", "Li", "Jing", "Qiao", "Lan", "Wei", "Feng", "Xia", "Ying", "Ting", "Yan", "Min", "Qian", "Yi", "Xue", "Ying", "Yue", "Hui", "Yong", "Qing", "Fang", "Cui", "Yan", "Hong", "Zi", "Juan", "Lan", "Xing", "Yan", "Li", "Qing", "Zhu", "Hui", "Xia", "Yan", "Yi", "Hua", "Min", "Xin", "Yun", "Lian", "Xia", "Li", "Ru", "Xiu", "Ying", "Yan", "Jia", "Hui", "Meng", "Ling", "Yan", "Li", "Ying", "Yan", "Xin", "Xia", "Fang", "Cui", "Xiu", "Yun", "Li", "Jing", "Yan", "Qian", "Zhen", "Rong", "Xia", "Yan", "Zi", "Xin"],
      last_names: ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Zhu", "Shen", "Zhou", "Wu", "Sun", "Ma", "Zhu", "Hu", "Guo", "He", "Gao", "Lin", "Lu", "Wang", "Wu", "Li", "Xu", "Xu", "Chen", "Sun", "Xie", "Xu", "Jin", "Huang", "Yuan", "Feng", "Wang", "Zhang", "Liu", "Wu", "Zhou", "Lin", "Wang", "Wu", "Wu", "Chen", "Sun", "Zhu", "Liang", "Zhao", "Yuan", "Xie", "Cao", "Zhang", "Wang", "Xu", "Wang", "Tang", "Zhang", "Li", "Li", "Deng", "Wang", "Liu", "Zhang", "Xu", "Chen", "Zheng", "Yang", "Chen", "Wang", "Zhang", "Wang", "Wu", "Wang", "Zhang", "Li", "Sun", "Wang", "Wu", "Li", "Chen", "Zhang", "Zhou", "Huang", "Wang", "Zhang", "Li", "Chen", "Zhang"]
    },
  
    korea: {
      male: ["Minho", "Joon", "Seok", "Hyun", "Hoon", "Jin", "Jiho", "Taehyun", "Yoon", "Kang", "Jisoo", "Sung", "Jaehyun", "Donghae", "Junho", "Jiyoung", "Yoseob", "Jinhwan", "Chanwoo", "Jisung", "Donghyun", "Sanghyuk", "Minjae", "Kyungho", "Haeun", "Woojin", "Hyukjae", "Jinwoo", "Byungchan", "Yohan", "Taeyang", "Hyunseung", "Kibum", "Sungmin", "Hakyeon", "Minseok", "Kyungsoo", "Jongin", "Yixing", "Wonho", "Changmin", "Hyunwoo", "Jisoo", "Jaejoong", "Siwon", "Jungkook", "Taeyong", "Jaemin", "Seungkwan", "Junghoon", "Sanghyun", "Jihoon", "Doyoung", "Younghoon", "Hyunsuk", "Jiwon", "Hyojin", "Hyungwon", "Jinseok", "Kihyun", "Seungmin", "Yonghoon", "Heejun", "Dongwon", "Jinseok", "Minhyuk", "Junghwan", "Seungyoon", "Jiyoung", "Hyeongjun", "Jonghyun", "Dohyun", "Sunghoon", "Geonu", "Hyunjin", "Kangmin", "Yugyeom", "Dohwan", "Taekyung", "Sangmin", "Jinhyuk", "Dohyun", "Sungjun", "Hyunwoo", "Junseok", "Taewoo", "Hwanhee", "Yeonjun", "Jiho", "Jihoon"],
      female: ["Eunji", "Sooyoung", "Minji", "Jiwon", "Jiyeon", "Haeun", "Hyunjin", "Seulgi", "Bomi", "Soyeon", "Yuna", "Soojin", "Yeonwoo", "Yujin", "Chaeyoung", "Eunbi", "Jisoo", "Nayeon", "Jennie", "Jisung", "Jisoo", "Hyejin", "Jisung", "Chaeyoung", "Soyoung", "Jiwon", "Heejin", "Yujin", "Seoyeon", "Sujin", "Seoyeon", "Jiwon", "Kyungwon", "Eunha", "Umji", "SinB", "Yerin", "Sowon", "Nari", "Eunha", "Hayoung", "Yewon", "Jiwon", "Hyunjin", "Mina", "Momo", "Sana", "Dahyun", "Chaeyoung", "Tzuyu", "Jihyo", "Seunghee", "Binnie", "Jiho", "Arin", "Chuu", "Yves", "Gowon", "Jinsoul", "Kimlip", "Chuu", "Yeonjung", "Dayoung", "Bona", "Xuan Yi", "Meiqi", "Cheng Xiao", "Eunseo", "Luda", "Dawon", "Bona", "Soobin", "Yeonjung", "Luda", "Seola", "Dawon", "Soobin", "Xiao", "Eunseo", "Meiqi", "Cheng Xiao", "Exy", "Wuju", "Sohee", "Seojeong", "Dami", "Jiu", "Sua", "Siyeon"],
      last_names: ["Kim", "Lee", "Park", "Choi", "Jeong", "Kang", "Song", "Yoon", "Han", "Yang", "Shin", "Oh", "Jung", "Kim", "Lee", "Park", "Choi", "Jeong", "Kang", "Song", "Yoon", "Han", "Yang", "Shin", "Oh", "Jung", "Hwang", "Chun", "Chung", "Yoo", "Nam", "Moon", "Lim", "Gim", "Joo", "Kwak", "Bae", "Kwon", "Hong", "Jo", "Chang", "Im", "Wi", "Won", "Baek", "Bang", "Dokgo", "Son", "Song", "Yun", "Na", "Noh", "Mok", "Myeong", "Sa", "Seo", "Sin", "Ryoo", "Yeom", "Won", "Hui", "Ko", "Go", "Gye", "Gui", "Gu", "Seok", "Seong", "Seol", "Seom", "Jeon", "Jin", "Ji", "Jin", "Jae", "Hyeon", "Hyo", "Hyun", "Hong", "Ha", "Han", "Heo", "Ho", "Hu", "Hwang", "Ho", "Hee", "Hoon", "Ha", "Hi", "Hyuk", "Yoon", "Yi", "Yeong", "Yeom"]
    },
  
    finland: {
      male: ["Eero", "Mikko", "Juhani", "Aapo", "Aleksi", "Antti", "Jani", "Juho", "Markus", "Matias", "Niko", "Oskari", "Otto", "Sami", "Timo", "Tomi", "Topi", "Ville", "Henri", "Ilari", "Jesse", "Joel", "Joni", "Joonas", "Juha", "Kalle", "Lauri", "Leo", "Mika", "Panu", "Pekka", "Petri", "Rasmus", "Sakari", "Sami", "Sebastian", "Teemu", "Tero", "Tomi", "Tuomas", "Veli-Matti", "Vesa", "Ville", "Yrjö", "Matti", "Heikki", "Eetu", "Roope", "Taneli", "Arto", "Elias", "Kustaa", "Anton", "Eemeli", "Jarkko", "Heikki", "Kari", "Kristian", "Eino", "Erkki", "Väinö", "Lauri", "Olavi", "Toivo", "Kustaa", "Ilmari", "Aarne", "Ensio", "Kalevi", "Valtteri", "Tapani", "Tapio", "Esko", "Jarmo", "Jukka", "Kari", "Mauri", "Reino", "Tapani", "Teuvo", "Väinö", "Arja", "Helena", "Hilkka", "Irmeli", "Jaana", "Kaisa", "Leena", "Maija", "Marja", "Outi", "Pirjo", "Riitta", "Sari", "Satu", "Tarja"],
      female: ["Aada", "Aino", "Anna", "Emilia", "Eveliina", "Helmi", "Henna", "Iida", "Inka", "Julia", "Kaisa", "Katri", "Lotta", "Maija", "Matilda", "Meeri", "Milla", "Minttu", "Nelli", "Nina", "Oona", "Paula", "Pia", "Reetta", "Riikka", "Rosa", "Saana", "Sara", "Silja", "Sofia", "Suvi", "Tanja", "Taru", "Tiina", "Ulla", "Veera", "Venla", "Vilma", "Emmi", "Annikki", "Elina", "Heli", "Iiris", "Johanna", "Kaarina", "Kati", "Kerttu", "Laura", "Linda", "Maria", "Marika", "Marita", "Marjut", "Mervi", "Minna", "Mirja", "Nina", "Noora", "Piia", "Riina", "Ritva", "Satu", "Sirpa", "Sisko", "Susanna", "Taina", "Tanja", "Tiina", "Tuija", "Ulla", "Veera", "Virpi", "Vuokko", "Hannele", "Annikka", "Elina", "Katariina", "Mari", "Kaarina", "Karoliina", "Lotta", "Johanna", "Hanna", "Iida", "Kerttu", "Marianne"],
      last_names: ["Korhonen", "Virtanen", "Mäkinen", "Nieminen", "Mäkelä", "Hämäläinen", "Laine", "Heikkinen", "Koskinen", "Järvinen", "Lehtonen", "Leppänen", "Kallio", "Saarinen", "Miettinen", "Peltola", "Hietala", "Aaltonen", "Manninen", "Koivisto", "Salo", "Rantanen", "Koivunen", "Lindholm", "Hakala", "Hiltunen", "Savolainen", "Laaksonen", "Kinnunen", "Tolonen", "Räsänen", "Karjalainen", "Salmela", "Laitinen", "Hirvonen", "Tuominen", "Mikkonen", "Koivula", "Väänänen", "Kuosmanen", "Jokinen", "Aho", "Väisänen", "Hakanen", "Laitala", "Ojanen", "Kaukonen", "Kujala", "Koskela", "Jokela", "Kuronen", "Viljanen", "Kortelainen", "Turunen", "Leinonen", "Ahola", "Kuosma", "Pakarinen", "Rautiainen", "Jussila", "Alanko", "Mielonen", "Mäki", "Kaukola", "Kekäläinen", "Kiviluoto", "Ikonen", "Pelkonen", "Hämynen", "Leinonen", "Kärkkäinen", "Palmu", "Palmroos", "Mäläskä", "Alanko", "Viljamaa", "Raatikainen", "Salin", "Niemi", "Keto", "Jutila", "Jutila", "Luotonen", "Pekkanen", "Eerola", "Aarnio", "Oksanen"]
    },
  
    austria: {
      male: ["Sebastian", "Alexander", "Felix", "Maximilian", "Leo", "Elias", "Luca", "Simon", "Julian", "Lukas", "David", "Daniel", "Paul", "Jakob", "Valentin", "Niklas", "Philipp", "Markus", "Tobias", "Jonathan", "Dominik", "Vincent", "Adrian", "Fabian", "Noah", "Moritz", "Benjamin", "Gabriel", "Anton", "Andreas", "Jonathan", "Max", "Raphael", "Julius", "Florian", "Matthias", "Samuel", "Emil", "Hannes", "Oskar", "Johannes", "Emmanuel", "Christian", "Sascha", "Emanuel", "Robert", "Richard", "Benedikt", "Emilio", "Marcel", "Tim", "Ferdinand", "Marian", "Jeremias", "Alfred", "Eduard", "Gustav", "Gregor", "Leonhard", "Albrecht", "Karl", "Rupert", "Wolfgang", "Franz", "Otto", "Ernst", "Heinrich", "Manfred", "Helmut", "Gerhard", "Dieter", "Werner", "Herbert", "Roland", "Walter", "Peter", "Thomas", "Hans", "Josef", "Kurt", "Klaus", "Rainer", "Wilhelm", "Georg", "Norbert", "Günther", "Rudolf", "Anton", "Stefan", "Hubert"],
      female: ["Sophie", "Lena", "Anna", "Emma", "Laura", "Hannah", "Julia", "Emilia", "Lea", "Lina", "Sarah", "Victoria", "Elena", "Marie", "Amelie", "Clara", "Nina", "Isabella", "Lara", "Eva", "Mia", "Lisa", "Paula", "Johanna", "Elisabeth", "Fiona", "Alina", "Melanie", "Magdalena", "Rosa", "Celine", "Sofia", "Ava", "Leona", "Sophia", "Livia", "Teresa", "Caroline", "Olivia", "Antonia", "Maja", "Klara", "Katharina", "Helena", "Nicole", "Valentina", "Raphaela", "Diana", "Selina", "Vanessa", "Mira", "Maria", "Gabriela", "Verena", "Linda", "Miriam", "Dorothea", "Anita", "Karin", "Barbara", "Petra", "Monika", "Elisabeth", "Renate", "Christine", "Martina", "Susanne", "Heidi", "Brigitte", "Gisela", "Waltraud", "Ingrid", "Ursula", "Hildegard", "Elfriede", "Ruth", "Edith", "Margarete", "Gertrude", "Anna", "Erika", "Hannelore", "Irmgard", "Eva", "Ilse", "Maria", "Erna", "Lieselotte"],
      last_names: ["Gruber", "Huber", "Bauer", "Wagner", "Müller", "Pichler", "Steiner", "Leitner", "Berger", "Fuchs", "Eder", "Aigner", "Mayr", "Schmid", "Schneider", "Schwarz", "Fischer", "Wimmer", "Lechner", "Hofer", "Moser", "Schuster", "Schmidt", "Maier", "Koch", "Weber", "Schweitzer", "Schneider", "Reiter", "Binder", "Friedl", "Egger", "Jung", "Hofmann", "Kreuzer", "Steininger", "Koller", "Reichl", "Haas", "Fellner", "Hermann", "Lang", "Winkler", "Lackner", "Pfeiffer", "Ebner", "Riegler", "Kaiser", "Pucher", "Stadler", "Böck", "Hollaus", "Buchinger", "Rosenberger", "Schachner", "Neubauer", "Pilz", "Seidl", "Vogel", "Rath", "Kölbl", "Zeiler", "Kogler", "Hacker", "Eibl", "Hofbauer", "Hofmann", "Lindner", "Plank", "Reisinger", "Scherer", "Strobl", "Schachinger", "Wiesinger", "König", "Pirker", "Fleischmann", "Falkner", "Braun", "Schranz", "Stöckl", "Dietrich", "Kogler", "Loidl", "Steinberger", "Pühringer", "Schmalz"]
    },
  
    hungary: {
      male: ["Bence", "Ádám", "Dávid", "Márk", "Levente", "Gergő", "Balázs", "Kristóf", "Zoltán", "Máté", "Péter", "András", "István", "Norbert", "Gábor", "Tamás", "Barnabás", "László", "Dániel", "Bálint", "János", "György", "Szabolcs", "Attila", "Sándor", "Viktor", "Milán", "Ferenc", "Csaba", "Zsolt", "Krisztián", "Richárd", "Varga", "Simon", "Balogh", "Tóth", "Nagy", "Kovács", "Farkas", "Szabó", "Molnár", "Kiss", "Takács", "Papp", "Horváth", "Lukács", "Antal", "Király", "Rácz", "Kocsis", "Bokor", "Barta", "Csernák", "Darányi", "Édes", "Füzesi", "Gulyás", "Hegedüs", "Iván", "Jámbor", "Kertész", "Lengyel", "Mészáros", "Nagy", "Ónodi", "Pálinkás", "Révész", "Szűcs", "Tóth", "Ürögi", "Vajda", "Vincze", "Zoltai", "Fodor", "Gáspár", "Hegedűs", "Illés", "Juhász", "Király", "Lantos", "Molnár", "Németh", "Orbán", "Pánczél", "Rózsa", "Salamon", "Szalai", "Török", "Vincze", "Varga"],
      female: ["Anna", "Lilla", "Zsófia", "Viktória", "Réka", "Eszter", "Petra", "Kata", "Dóra", "Noémi", "Boglárka", "Kinga", "Léna", "Laura", "Júlia", "Krisztina", "Barbara", "Flóra", "Diana", "Bianka", "Maja", "Zita", "Vivien", "Sára", "Evelin", "Emma", "Hanna", "Adrienn", "Szofia", "Katalin", "Erika", "Fanni", "Zsuzsa", "Mónika", "Nikolett", "Irén", "Orsolya", "Jázmin", "Ildikó", "Judit", "Melinda", "Ella", "Henrietta", "Lilla", "Rebeka", "Dalma", "Tímea", "Vanda", "Veronika", "Dalma", "Fruzsina", "Virág", "Anita", "Bernadett", "Etelka", "Gyöngyi", "Jolán", "Kornélia", "Zsuzsanna", "Edina", "Bori", "Eszti", "Gabriella", "Hedvig", "Izabella", "Julianna", "Lívia", "Nelli", "Rozália", "Sári", "Valéria", "Xénia", "Zsanett", "Amira", "Csilla", "Diána", "Henrietta", "Ilona", "Janka", "Kamilla", "Lili", "Magdolna", "Nóra", "Ramóna", "Soma", "Tünde", "Vanda", "Zselyke", "Zsanett"],
      last_names: ["Nagy", "Kovács", "Varga", "Tóth", "Balogh", "Horváth", "Kiss", "Molnár", "Szabó", "Juhász", "Farkas", "Takács", "Papp", "Németh", "Balázs", "Lengyel", "Barta", "Király", "Bokor", "Csernák", "Darányi", "Édes", "Füzesi", "Gulyás", "Hegedüs", "Iván", "Jámbor", "Kertész", "Szűcs", "Tóth", "Ürögi", "Vajda", "Vincze", "Zoltai", "Fodor", "Gáspár", "Hegedűs", "Illés", "Lantos", "Nagy", "Ónodi", "Pálinkás", "Révész", "Szalai", "Török", "Varga", "Mészáros", "Simon", "Balogh", "Tóth", "Nagy", "Kovács", "Farkas", "Szabó", "Molnár", "Kiss", "Takács", "Papp", "Horváth", "Lukács", "Antal", "Király", "Rácz", "Kocsis", "Bokor", "Barta", "Csernák", "Darányi", "Édes", "Füzesi", "Gulyás", "Hegedüs", "Iván", "Jámbor", "Kertész", "Lengyel", "Mészáros", "Nagy", "Ónodi", "Pálinkás", "Révész", "Szűcs", "Tóth", "Ürögi", "Vajda", "Vincze", "Zoltai"]
    },
  
    iceland: {
      male: ["Björn", "Jón", "Ólafur", "Einar", "Gunnar", "Sigurður", "Magnús", "Stefán", "Kristján", "Hafþór", "Hannes", "Andri", "Þór", "Birkir", "Valdimar", "Ari", "Arnar", "Guðmundur", "Helgi", "Ingvar", "Árni", "Viktor", "Kári", "Eiríkur", "Ragnar", "Finnur", "Haukur", "Emil", "Gísli", "Freyr", "Sveinn", "Lárus", "Rúnar", "Þorsteinn", "Bjarni", "Snorri", "Hjalti", "Hilmar", "Baldur", "Hörður", "Leifur", "Eysteinn", "Brynjar", "Örn", "Kjartan", "Andreas", "Atli", "Daníel", "Gunnlaugur", "Hjörtur", "Ívar", "Jökull", "Kolbeinn", "Mikael", "Njáll", "Orri", "Pétur", "Róbert", "Steinar", "Teitur", "Unnar", "Vigfús", "Þráinn", "Þröstur", "Þórarinn", "Ævar", "Örnólfur", "Örvar", "Örn", "Örnólfur", "Örvar"],
      female: ["Anna", "Sigríður", "Helga", "Guðrún", "Kristín", "María", "Berglind", "Hanna", "Elín", "Þórdís", "Ásta", "Eva", "Júlía", "Bryndís", "Margrét", "Rakel", "Dís", "Hulda", "Edda", "Þórunn", "Sara", "Lilja", "Katrín", "Ingibjörg", "Hildur", "Sunna", "Íris", "Dagný", "Arna", "Agnes", "Hafdís", "Birta", "Björt", "Emelía", "Fanney", "Freyja", "Guðbjörg", "Guðný", "Gunnhildur", "Harpa", "Hrafnhildur", "Jóhanna", "Kolbrún", "Lára", "Magdalena", "Nanna", "Rósa", "Saga", "Salóme", "Sesselja", "Silja", "Sólveig", "Sólrún", "Stella", "Unnur", "Valdís", "Vigdís", "Ýr", "Þrúður", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís", "Þórdís"],
      last_names: ["Jónsson", "Björnsson", "Ólafsson", "Einarsson", "Gunnarsson", "Sigurðsson", "Magnússon", "Stefánsson", "Kristjánsson", "Hafþórsson", "Hannesson", "Andresson", "Þórsson", "Birkisson", "Valdimarsson", "Arisson", "Arnarsson", "Guðmundsson", "Helgason", "Ingvarsson", "Árnesson", "Viktorsson", "Kárison", "Eiríksson", "Ragnarsson", "Finnursson", "Haukursson", "Emilsson", "Gíslason", "Freyrsson", "Sveinsson", "Lársson", "Rúnarsson", "Þorsteinsson", "Bjarnason", "Snorrason", "Hjaltisson", "Hilmarrson", "Baldursson", "Hörðursson", "Leifursson", "Eysteinsson", "Brynjarrson", "Örnsson", "Kjartansson", "Andreasson", "Atlasson", "Daníelsson", "Gunnlaugsson", "Hjörtursson", "Ívarsson", "Jökullsson", "Kolbeinsson", "Mikaelsson", "Njállson", "Orrisson", "Pétursson", "Róbertsson", "Steinarsson", "Teitsson", "Unnarsson", "Vigfússon", "Þráinnsson", "Þröstursson", "Þórarinnsson", "Ævarsson", "Örnólfursson", "Örvarsson", "Örnsson", "Örnólfursson", "Örvarsson"]
    },
  
    belgium: {
      male: ["Lucas", "Liam", "Thomas", "Ethan", "Noah", "Louis", "Adam", "Mathis", "Victor", "Arthur", "Leo", "Nathan", "Mohamed", "Samuel", "Hugo", "Alexandre", "Maxime", "Jules", "Gabriel", "Elias", "Alexander", "Finn", "Matteo", "Rayan", "Milan", "Oscar", "Lars", "Sebastian", "David", "Julien", "Diego", "Luca", "Robin", "Simon", "Raphael", "Aaron", "Théo", "Paul", "Milo", "Xander", "Aiden", "Nolan", "Sander", "Emile", "Jasper", "Matthias", "Emil", "Joren", "Sam", "Kobe", "Brent", "Wout", "Yannick", "Quinten", "Niels", "Laurent", "Guillaume", "Romain", "Philippe", "Cédric", "Maxime", "Olivier", "Jonathan", "Sébastien", "Vincent", "Thibault", "Michaël", "Damien", "Cyril", "Grégory", "Antoine", "Nicolas", "Pierre", "Benjamin", "Adrien", "Axel", "Valentin", "Alexis", "Baptiste", "Florent", "Luc", "Stéphane", "François", "Jean", "Paul", "Jacques", "André"],
      female: ["Emma", "Olivia", "Louise", "Alice", "Lina", "Mila", "Ella", "Anna", "Julia", "Amelia", "Elena", "Camille", "Zoe", "Nora", "Eva", "Chloe", "Léa", "Manon", "Charlotte", "Lara", "Sarah", "Fleur", "Nina", "Sophie", "Elise", "Clara", "Lily", "Juliette", "Rose", "Aya", "Sofia", "Lana", "Luna", "Mia", "Emily", "Marie", "Lucie", "Alix", "Célia", "Noémie", "Ines", "Lola", "Amelie", "Ambre", "Eline", "Iris", "Hannah", "Megan", "Laura", "Eline", "Fien", "Pauline", "Yasmine", "Lea", "Amber", "Tess", "Estelle", "Lien", "Maud", "Axelle", "Eléonore", "Mathilde", "Nathalie", "Marine", "Caroline", "Margaux", "Aurélie", "Sylvie", "Valérie", "Isabelle", "Christine", "Aline", "Martine", "Danielle", "Nicole", "Claire", "Monique", "Hélène", "Anne", "Catherine", "Françoise", "Véronique", "Brigitte", "Sophie", "Myriam", "Sabine"],
      last_names: ["Peeters", "Janssens", "Maes", "Jacobs", "Mertens", "Willems", "Claes", "Goossens", "Wouters", "De Smet", "Dubois", "Vermeulen", "Lambrechts", "Van Damme", "Wouters", "Van den Broeck", "Jansen", "Smets", "Verschueren", "De Cock", "De Vos", "Pauwels", "De Backer", "Dewitte", "Bogaerts", "Vandenberghe", "Lemmens", "Vandamme", "Vandenbergh", "De Pauw", "Desmet", "Michiels", "Bosmans", "Vandenberg", "Coppens", "De Wit", "De Bock", "Lenaerts", "Vermeyen", "Dewaele", "Bogaert", "Frans", "Vandecasteele", "De Ridder", "Goossens", "Hermans", "Vandevenne", "Geerts", "Vangenechten", "Van Loon", "De Coninck", "Vercammen", "De Buysser", "De Waele", "De Wilde", "Verhaegen", "Vanderlinden", "De Cooman", "De Moor", "De Bie", "Bogaert", "De Keersmaecker", "Van den Bosch", "De Maeyer", "Lemmens", "Verbruggen", "Driesen", "Van Doorslaer", "Lauwers", "Van de Velde", "Van den Berg", "Verheyen", "Michielsen", "De Vriendt", "Mortier", "Van Bavel", "Cools", "Vanderveken", "Vermeersch", "Van Riel", "Bervoets", "Vermeiren", "Dejonghe", "De Boeck", "Thys", "Verstraelen"]
    },
  
    yemen: {
      male: ["Mohammed", "Ahmed", "Abdullah", "Ali", "Omar", "Youssef", "Khalid", "Ismail", "Tariq", "Hassan", "Hamza", "Sami", "Yasin", "Faisal", "Saad", "Nasser", "Amir", "Nabil", "Zaid", "Waleed", "Hadi", "Adel", "Osama", "Jamil", "Raed", "Majed", "Tamer", "Karam", "Rami", "Fadi", "Bilal", "Ibrahim", "Mustafa", "Salim", "Naji", "Riyad", "Mahmoud", "Salem", "Yahya", "Hisham", "Nawaf", "Kareem", "Qasim", "Mansoor", "Anwar", "Nidal", "Ashraf", "Mazen", "Ayman", "Akram", "Sharif", "Zakaria", "Nizar", "Yaser", "Rashid", "Moeen", "Ammar", "Naji", "Aziz", "Hatem", "Rafiq", "Farid", "Karim", "Abdo", "Said", "Talal", "Wael", "Fahad", "Ismail", "Sufyan", "Othman", "Khaled", "Jamal", "Amin", "Naeem", "Wasim", "Hussein", "Rafat", "Taher", "Tawfiq", "Fawaz", "Zuhair", "Ezzat", "Ghazi", "Nizar", "Bashir", "Adnan", "Muhannad", "Othman", "Aziz"],
      female: ["Fatima", "Aisha", "Noura", "Layla", "Khadija", "Sara", "Mona", "Hana", "Amal", "Samira", "Lina", "Randa", "Safia", "Dalal", "Jamila", "Rasha", "Zainab", "Maha", "Roula", "Hanan", "Najla", "Nada", "Nadia", "Noor", "Dina", "Hayat", "Huda", "Salma", "Farida", "Yasmin", "Wafa", "Ibtisam", "Nawal", "Naima", "Maya", "Sabah", "Faten", "Mai", "Asma", "Basma", "Rima", "Nisreen", "Bushra", "Sawsan", "Siham", "Amani", "Nadia", "Sanaa", "Najwa", "Abeer", "Ghada", "Rabab", "Afaf", "Hala", "Lamia", "Dalia", "Afaf", "Fadia", "Nashwa", "Habiba", "Suad", "Hanan", "Rabia", "Nour", "Reem", "Safia", "Ihsan", "Zahra", "Saida", "Rahma", "Aida", "Amina", "Rukaya", "Asmahan", "Lubna", "Malak", "Rula", "Najat", "Wijdan", "Maysa", "Raja", "Zakia", "Nisrin", "Amira"],
      last_names: ["Hakimi", "Mansoori", "Faqih", "Bahri", "Dhahab", "Hajj", "Amoudi", "Hashmi", "Mutawakel", "Harazi", "Hadi", "Rahbi", "Ghazi", "Nashiri", "Sakkaf", "Wazir", "Sulaimani", "Qubati", "Jabri", "Houthi", "Maqtari", "Saqqaf", "Mikhlafi", "Absi", "Masri", "Khader", "Yazidi", "Zubairi", "Maamari", "Mutairi", "Qahtani", "Badri", "Sabri", "Raqqi", "Rawhani", "Zahrani", "Qurashi", "Dabagh", "Fadhli", "Maghribi", "Sharif", "Attar", "Jabarti", "Khatib", "Amin", "Madhaji", "Maliki", "Kubaisi", "Khudari", "Khawlani", "Zubeidi", "Obaidi", "Mahjoub", "Dosari", "Qaysi", "Ashja'i", "Murshid", "Rawi", "Haddad", "Daghari", "Rifai", "Barghouthi", "Baghawi", "Mustafa", "Ashraf", "Khalidi", "Sheibani", "Jishi", "Fakih"]
    },
  
    zimbabwe: {
      male: ["Tinashe", "Farai", "Tapiwa", "Kudzai", "Tanaka", "Simba", "Tatenda", "Tawanda", "Tonderai", "Brighton", "Tariro", "Tadiwa", "Munyaradzi", "Kundai", "Tafadzwa", "Terrence", "Lungile", "Takudzwa", "Munashe", "Ngonidzashe", "Tawanda", "Kuziva", "Tichaona", "Farirai", "Tendai", "Tapiwanashe", "Mudiwa", "Nyasha", "Tatenda", "Nigel", "Rufaro", "Takura", "Njabulo", "Nkosana", "Makomborero", "Tatendaishe", "Mufaro", "Tawanda", "Wisdom", "Kupakwashe", "Thabani", "Tatenda", "Tinotenda", "Siyabonga", "Tinaye", "Thando", "Nokuthula", "Sibusiso", "Nqobile", "Mthokozisi", "Mhlengi", "Muzi", "Lindani", "Mandla", "Thulani", "Zibusiso", "Njabulo", "Lungelo", "Sandile", "Sizwe", "Melusi", "Zwelithini", "Mqondisi", "Ndabezinhle", "Sithembiso", "Mxolisi", "Zithulele", "Zondani", "Bhekinkosi", "Senzekhaya", "Bongani", "Khwezi", "Mandlenkosi", "Lungisani", "Sipho", "Thokozani", "Lwazi", "Phumlani", "Vuyisile", "Thamsanqa", "Kwanele", "Ayanda", "Sikhumbuzo"],
      female: ["Chipo", "Nyasha", "Rudo", "Tariro", "Tafadzwa", "Tendai", "Tsitsi", "Panashe", "Shamiso", "Ruvarashe", "Nyarai", "Tashinga", "Tapiwa", "Tanatswa", "Tadiwa", "Kundai", "Tawanda", "Makomborero", "Mudiwa", "Tatenda", "Loveness", "Precious", "Tinotenda", "Takudzwa", "Nokuthula", "Norest", "Fadzai", "Munashe", "Ngonidzashe", "Kuziva", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita", "Maita"],
      last_names: ["Moyo", "Ncube", "Sibanda", "Dube", "Ndlovu", "Zulu", "Mlambo", "Mhlanga", "Mukono", "Chikomo", "Nyathi", "Chikukwa", "Machemedze", "Manyika", "Gumbo", "Shumba", "Mazibuko", "Chirwa", "Chakabuda", "Denga", "Gwatidzo", "Gwaze", "Gwaze", "Chisango", "Munyeza", "Zvirawa", "Mapfumo", "Masunda", "Makumucha", "Goredema", "Kasirori", "Shoko", "Chipunza", "Majongwe", "Kurebwaseka", "Tendai", "Matenda", "Kasamba", "Chandamhara", "Chirikure", "Chakabuda", "Chinhoyi", "Chikasha", "Dzinotizei", "Gora", "Gwaze", "Gwangwava", "Gwatidzo", "Chibanda", "Kasirori", "Kufahakutizwi", "Madzongwe", "Mafirakureva", "Makanyanga", "Manunure", "Mapondera", "Mashayamombe", "Mubayiwa", "Mubvumbi", "Mudzimurema", "Mukarakate", "Mumvuma", "Munhutu", "Mutakwa", "Mutenhesanwa", "Mutori", "Mutseka", "Nemakonde", "Ngugama", "Nhamburo", "Nherera", "Nyahwo", "Nyamayaro", "Nyamhandu", "Nyamweda", "Nyamweda", "Nyaradzo", "Nyemba", "Nyoni", "Shumira", "Takabvirwa", "Tariro", "Tengende", "Tichatonga", "Tsikwa"]
    },
  
    russia: {
      male: ["Ivan", "Alexei", "Dmitry", "Vladimir", "Nikolai", "Mikhail", "Artem", "Andrei", "Sergei", "Pavel", "Yuri", "Viktor", "Denis", "Anton", "Konstantin", "Oleg", "Roman", "Maxim", "Igor", "Boris", "Fedor", "Alexandr", "Grigory", "Leonid", "Anatoly", "Evgeny", "Kirill", "Nikita", "Vitaly", "Ilya", "Dmitri", "Egor", "Timur", "Ruslan", "Semyon", "Nikita", "Sergey", "Valentin", "Igor", "Maksim", "Dmitriy", "Aleksandr", "Aleksey", "Yaroslav", "Oleg", "Yevgeny", "Aleksandr", "Dmitry", "Konstantin", "Vladislav", "Ruslan", "Petr", "Andrey", "Vladislav", "Vyacheslav", "Ilya", "Artyom", "Nikolay", "Sergey", "Vladimir", "Ivan", "Andrei", "Mikhail", "Pavel", "Kirill", "Dmitry", "Anton", "Aleksandr", "Artem", "Alexei", "Denis", "Viktor", "Maxim", "Igor", "Roman", "Yuri", "Nikolai", "Fedor", "Boris", "Anatoly", "Grigory", "Sergei", "Leonid", "Evgeny", "Konstantin", "Oleg", "Ilya", "Dmitri", "Egor", "Nikita"],
      female: ["Olga", "Tatiana", "Svetlana", "Natalia", "Anna", "Irina", "Ekaterina", "Elena", "Maria", "Yelena", "Daria", "Ksenia", "Anastasia", "Yulia", "Polina", "Alyona", "Alexandra", "Victoria", "Marina", "Darya", "Yekaterina", "Alina", "Nina", "Eva", "Lyudmila", "Nadezhda", "Galina", "Lyubov", "Valentina", "Tatyana", "Rimma", "Iraida", "Yaroslava", "Larisa", "Yana", "Kira", "Sofia", "Vera", "Veronika", "Margarita", "Taisiya", "Ekaterina", "Nina", "Mariya", "Lidiya", "Irina", "Tamara", "Diana", "Angelina", "Karina", "Anastasiya", "Lilia", "Evgeniya", "Natalya", "Elena", "Anna", "Irina", "Olga", "Tatiana", "Svetlana", "Elena", "Natalia", "Ksenia", "Anastasia", "Ekaterina", "Alexandra", "Polina", "Yulia", "Marina", "Daria", "Alyona", "Victoria", "Anna", "Irina", "Olga", "Tatiana", "Svetlana", "Elena", "Natalia", "Ksenia", "Anastasia", "Ekaterina", "Alexandra", "Polina"],
      last_names: ["Ivanov", "Smirnov", "Kuznetsov", "Popov", "Vasilyev", "Petrov", "Sokolov", "Mikhailov", "Fedorov", "Morozov", "Novikov", "Orlov", "Kozlov", "Volkov", "Lebedev", "Semenov", "Egorov", "Nikolaev", "Kovalenko", "Zaitsev", "Pavlov", "Gusev", "Sorokin", "Ivanova", "Smirnova", "Kuznetsova", "Popova", "Vasilyeva", "Petrova", "Sokolova", "Mikhailova", "Fedorova", "Morozova", "Novikova", "Orlova", "Kozlova", "Volkova", "Lebedeva", "Semenova", "Egorova", "Nikolaeva", "Kovalenko", "Zaitseva", "Pavlova", "Guseva", "Sorokina", "Dubrov", "Lobachev", "Suvorov", "Antonov", "Artemiev", "Dmitriev", "Bogdanov", "Grigoriev", "Vorobiev", "Zakharov", "Romanov", "Kozlov", "Makarov", "Nikitin", "Zakharova", "Romanova", "Makarova", "Nikitina", "Golubev", "Korolev", "Zaytsev", "Golubeva", "Koroleva", "Zaytseva", "Vorobyeva", "Igoreva", "Sergeeva", "Igorevna", "Sergeevna", "Andreeva", "Mironova", "Vasilev", "Grigorev", "Davydov", "Vasileva", "Davydova", "Grigorieva", "Zhukova", "Lazarev", "Zhukov"]
    },
  
    ukraine: {
      male: ["Oleksandr", "Andriy", "Mykhailo", "Volodymyr", "Ivan", "Petro", "Serhiy", "Oleg", "Yuriy", "Anatoliy", "Viktor", "Denys", "Artem", "Taras", "Roman", "Dmytro", "Bogdan", "Yaroslav", "Ihor", "Maksym", "Andriy", "Ostap", "Vasyl", "Sviatoslav", "Oleksiy", "Kyrylo", "Ilya", "Anton", "Bohdan", "Hryhoriy", "Ostap", "Oleksiy", "Yevhen", "Vladyslav", "Zakhar", "Vladimir", "Nikita", "Mykola", "Yaroslav", "Yakov", "Arseniy", "Ivan", "Leonid", "Andriy", "Vitaliy", "Maksym", "Vsevolod", "Yegor", "Vladislav", "Sergiy", "Denys", "Olexiy", "Borys", "Andriy", "Serhiy", "Miroslav", "Viktor", "Oleh", "Igor", "Bohdan", "Yan", "Ostap", "Olexandr", "Yaroslav", "Ostap", "Kyrylo", "Bogdan", "Danylo", "Oleksiy", "Vasyl", "Mykola", "Vlad", "Dmytro", "Kyrylo", "Bohdan", "Artem", "Serhiy", "Andriy", "Denys", "Maksym", "Oleksandr", "Roman", "Yaroslav", "Vladyslav", "Ostap", "Andriy", "Vitaliy", "Dmytro", "Oleksandr", "Serhiy", "Maksym", "Andriy", "Ostap"],
      female: ["Anastasiia", "Maria", "Olena", "Yulia", "Olga", "Iryna", "Nataliia", "Tetiana", "Anna", "Kateryna", "Viktoriia", "Diana", "Valeriia", "Khrystyna", "Ivanna", "Alina", "Viktoria", "Karina", "Veronika", "Sofia", "Angelina", "Ksenia", "Lilia", "Yana", "Oleksandra", "Mariia", "Ivanna", "Nina", "Larysa", "Liudmyla", "Nadiia", "Yelyzaveta", "Irina", "Anna", "Olesia", "Vira", "Yaroslava", "Nataliia", "Tamara", "Valentyna", "Ruslana", "Olha", "Kateryna", "Yuliia", "Nataliia", "Karolina", "Marina", "Valeria", "Marianna", "Dariia", "Yevheniia", "Svitlana", "Nadiya", "Hanna", "Vita", "Yana", "Vlada", "Kristina", "Oksana", "Karyna", "Elizaveta", "Lina", "Diana", "Anastasiia", "Yaroslava", "Olena", "Tetiana", "Karina", "Oksana", "Alona", "Iryna", "Ivanna", "Valeriia", "Sofia", "Nataliia", "Veronika", "Yuliia", "Ksenia", "Kateryna", "Oleksandra", "Angelina", "Mariia", "Lilia", "Alina", "Viktoria", "Ivanna", "Diana", "Valeriia", "Khrystyna", "Iryna", "Nina"],
      last_names: ["Kovalenko", "Bondarenko", "Tkachenko", "Kozlov", "Moroz", "Pavlov", "Boiko", "Savchenko", "Koval", "Kovalchuk", "Omelchenko", "Shevchenko", "Shcherbak", "Polishchuk", "Kushnir", "Yakovenko", "Lysenko", "Ivanov", "Petrov", "Sidorov", "Popov", "Ivanova", "Petrova", "Sidorova", "Popova", "Kuznetsova", "Orlova", "Smirnova", "Mikhailova", "Egorova", "Nikitina", "Novikova", "Fedorova", "Morozova", "Guseva", "Ermakova", "Vasilieva", "Omelchenko", "Vorobeva", "Belova", "Savchenko", "Koroleva", "Titova", "Makarova", "Kozlova", "Bogdanova", "Shcherbakova", "Boiko", "Shevchenko", "Koval", "Omelchenko", "Kovalchuk", "Tkachenko", "Bondarenko", "Kozlov", "Pavlov", "Moroz", "Savchenko", "Boiko", "Shevchenko", "Koval", "Kovalchuk", "Omelchenko", "Tkachenko", "Bondarenko", "Kozlov", "Pavlov", "Moroz", "Savchenko", "Boiko", "Shevchenko", "Koval", "Kovalchuk", "Omelchenko", "Tkachenko", "Bondarenko", "Kozlov", "Pavlov", "Moroz", "Savchenko", "Boiko", "Shevchenko"]
    },
  
    qatar: {
      male: ["Ahmed", "Mohammed", "Khalid", "Yousef", "Abdullah", "Saud", "Hamad", "Faisal", "Nasser", "Jassim", "Rashid", "Saad", "Ali", "Omar", "Hassan", "Adnan", "Tariq", "Ibrahim", "Majid", "Saleh", "Kareem", "Bader", "Nawaf", "Hadi", "Amin", "Yasin", "Salem", "Rami", "Nabil", "Mansoor", "Rami", "Marwan", "Hussein", "Raed", "Tamer", "Zaid", "Osama", "Talal", "Waleed", "Fahad", "Bilal", "Hisham", "Kamil", "Basim", "Akram", "Ammar", "Munir", "Tayeb", "Sameer", "Nizar", "Tawfiq", "Farid", "Jalal", "Naji", "Wael", "Zuhair", "Rami", "Imad", "Nidal", "Nael", "Jawad", "Kais", "Samir", "Khalifa", "Fadi", "Zakariya", "Ismail", "Walid", "Jaber", "Hazem", "Hassam", "Jamal", "Rafiq", "Nasir", "Zaki", "Amer", "Karim", "Lutfi", "Kassem", "Wassim", "Hani", "Nizar", "Rami", "Ziad", "Haytham", "Tamer", "Moe", "Ghassan"],
      female: ["Fatima", "Aisha", "Mariam", "Layla", "Noor", "Sara", "Joud", "Reem", "Hala", "Noura", "Lina", "Hanan", "Amal", "Rana", "Dalal", "Haya", "Maha", "Samira", "Nadia", "Hayat", "Maya", "Mona", "Lulu", "Wafa", "Shaima", "Lubna", "Faten", "Zainab", "Zahra", "Basma", "Safia", "Salma", "Dana", "Asma", "Najla", "Nawal", "Samar", "Safa", "Ibtisam", "Abeer", "Rima", "Rasha", "Nada", "Hind", "Widad", "Amani", "Habiba", "Farida", "Sana", "Zain", "Jamila", "Nadia", "Layan", "Maha", "Riham", "Roula", "Maysa", "Houda", "Dina", "Afaf", "Hayfa", "Fadia", "Dalia", "Nisreen", "Hanadi", "Nibal", "Iman", "Rabab", "Shaza", "Buthayna", "Samah", "Iffat", "Wijdan", "Nisrin", "Lamis", "Sahar", "Siham", "Ghada", "Nagwa", "Munira", "Ahlam", "Hanan", "Zahia", "Zalfa", "Rahma", "Nahla", "Gada", "Madiha"],
      last_names: ["Abdul", "Ahmed", "Mohammed", "Khalid", "Yousef", "Saud", "Hamad", "Faisal", "Nasser", "Jassim", "Rashid", "Saad", "Ali", "Omar", "Hassan", "Adnan", "Tariq", "Ibrahim", "Majid", "Saleh", "Kareem", "Bader", "Nawaf", "Hadi", "Amin", "Yasin", "Salem", "Rami", "Nabil", "Mansoor", "Rami", "Marwan", "Hussein", "Raed", "Tamer", "Zaid", "Osama", "Talal", "Waleed", "Fahad", "Bilal", "Hisham", "Kamil", "Basim", "Akram", "Ammar", "Munir", "Tayeb", "Sameer", "Nizar", "Tawfiq", "Farid", "Jalal", "Naji", "Wael", "Zuhair", "Rami", "Imad", "Nidal", "Nael", "Jawad", "Kais", "Samir", "Khalifa", "Fadi", "Zakariya", "Ismail", "Walid", "Jaber", "Hazem", "Hassam", "Jamal", "Rafiq", "Nasir", "Zaki", "Amer", "Karim", "Lutfi", "Kassem", "Wassim", "Hani", "Nizar", "Rami", "Ziad", "Haytham", "Tamer", "Moe", "Ghassan"]
    },
  
    brazil: {
      male: ["Lucas", "Enzo", "Gabriel", "Pedro", "Mateus", "Arthur", "Bernardo", "Matheus", "Rafael", "Gustavo", "Felipe", "João", "Daniel", "Vinícius", "Leonardo", "Henrique", "Murilo", "Heitor", "Samuel", "Vitor", "Caio", "Davi", "Luiz", "Eduardo", "Diego", "André", "Nicolas", "Antônio", "Carlos", "Raul", "Fernando", "Miguel", "Renan", "Cauã", "Marcelo", "Ricardo", "Thiago", "Joaquim", "Júlio", "Joel", "Paulo", "Francisco", "Adriano", "Luciano", "Alexandre", "Ronaldo", "Hugo", "Isaac", "Emanuel", "Victor", "Alan", "Roberto", "Adriel", "Cristiano", "Ruan", "Alex", "Rafael", "Igor", "Juliano", "Leandro", "Lucas", "Felipe", "Robson", "Vinícius", "Matias", "Danilo", "Guilherme", "Emmanuel", "Luan", "José", "Elias", "Marcos", "Anderson", "Nathan", "Thiago", "Rogério", "Sérgio", "Jonathan", "Renato", "Lucas", "Vinícius", "Denis", "Adilson", "Erick", "Raphael", "Augusto", "Nícolas", "Rui"],
      female: ["Ana", "Julia", "Alice", "Manuela", "Isabella", "Laura", "Luiza", "Giovanna", "Maria", "Beatriz", "Mariana", "Yasmin", "Lara", "Heloísa", "Lívia", "Camila", "Larissa", "Rafaela", "Carolina", "Isabelly", "Eduarda", "Letícia", "Fernanda", "Clara", "Gabriela", "Mirella", "Vitória", "Bianca", "Laís", "Nicole", "Amanda", "Laisa", "Sophia", "Gabrielle", "Lorena", "Júlia", "Nathália", "Stella", "Elisa", "Raissa", "Nayara", "Yasmim", "Isis", "Rayssa", "Valentina", "Emily", "Alícia", "Melissa", "Livia", "Izabella", "Emilly", "Rafaela", "Catarina", "Evelyn", "Elaine", "Ayla", "Heloise", "Nicolly", "Cláudia", "Rebeca", "Lilian", "Jaqueline", "Vanessa", "Maria", "Ana", "Luiza", "Patrícia", "Valéria", "Lívia", "Elaine", "Eliana", "Roberta", "Clarice", "Natalia", "Carmen", "Gabriela", "Márcia", "Rosa", "Adriana", "Luciana", "Jéssica", "Elisa", "Aline", "Flávia", "Débora", "Renata", "Carla", "Mariana", "Fernanda", "Julieta"],
      last_names: ["Silva", "Santos", "Oliveira", "Souza", "Pereira", "Lima", "Carvalho", "Costa", "Almeida", "Martins", "Araújo", "Fernandes", "Rodrigues", "Gomes", "Nascimento", "Cavalcanti", "Melo", "Barbosa", "Sá", "Correia", "Cardoso", "Pinto", "Barros", "Ribeiro", "Monteiro", "Teixeira", "Moura", "Andrade", "Lopes", "Ferreira", "Santana", "Gonçalves", "Vieira", "Sousa", "Ramos", "Castro", "Cruz", "Marques", "Pires", "Freitas", "Vasconcelos", "Campos", "Dias", "Machado", "Moreira", "Tavares", "Lira", "Figueiredo", "Mendes", "Sales", "Garcia", "Pimentel", "Azevedo", "Novaes", "Borges", "Freire", "Couto", "Farias", "Cordeiro", "Reis", "Alves", "Magalhães", "Luz", "Paiva", "Cunha", "Motta", "Cabrera", "Godoy", "Pacheco", "Leite", "Aguiar", "Siqueira", "Bonfim", "Oliveira", "Lins", "Xavier", "Gusmão", "Bittencourt", "Peixoto", "Pontes", "Fonseca", "Prado", "Cruz", "Vidal", "Cavalcante", "Rocha", "Costa", "Vargas", "Guedes"]
    },
  
    oman: {
      male: ["Ali", "Mohammed", "Ahmed", "Salem", "Omar", "Abdullah", "Khalid", "Yousef", "Saud", "Hassan", "Majid", "Rashid", "Sultan", "Nasser", "Saif", "Ibrahim", "Hamad", "Khamis", "Fahad", "Jaber", "Tariq", "Nawaf", "Mansoor", "Khalifa", "Saeed", "Amin", "Mahmoud", "Hussein", "Jassim", "Kasim", "Faisal", "Talib", "Salim", "Yaqoob", "Rami", "Hadi", "Osama", "Adel", "Waleed", "Nabil", "Mubarak", "Jamil", "Rami", "Issa", "Tamer", "Raed", "Nizar", "Mazen", "Imad", "Zakariya", "Tawfiq", "Ziyad", "Ammar", "Adnan", "Amer", "Muhannad", "Nidal", "Khaled", "Rami", "Naeem", "Sameer", "Yassin", "Karim", "Zuhair", "Faris", "Asem", "Raafat", "Ismail", "Ayman", "Luay", "Wael", "Muhamed", "Joud", "Hazem", "Bassel", "Jihad", "Nael", "Samir", "Othman", "Ghassan", "Fadi", "Nizar", "Nidal", "Kassem", "Walid", "Ahmad", "Husam", "Bader", "Nassim", "Osman", "Riad", "Fayez", "Amer", "Rafiq", "Sari"],
      female: ["Fatima", "Aisha", "Mariam", "Noor", "Huda", "Zainab", "Layla", "Amina", "Maya", "Noura", "Sara", "Lina", "Nada", "Maha", "Amani", "Rana", "Dalal", "Amal", "Samira", "Jamila", "Hanan", "Leila", "Salma", "Roula", "Dana", "Safia", "Fatemeh", "Hayat", "Batool", "Afaf", "Asma", "Sabah", "Shaima", "Hessa", "Shaza", "Ibtisam", "Muna", "Najla", "Jawaher", "Nadia", "Shahad", "Khadija", "Suad", "Asmaa", "Lubna", "Wafa", "Ghada", "Hanan", "Sawsan", "Naima", "Najwa", "Rasha", "Muna", "Maysa", "Manal", "Rima", "Samar", "Fayza", "Mai", "Ola", "Abeer", "Rabab", "Noha", "Hanadi", "Rawan", "Nourhan", "Siham", "Nour", "Nawal", "Lamya", "Lamia", "Nora", "Shireen", "Sahar", "Hind", "Nisreen", "Farida", "Sabiha", "Inas", "Wijdan", "Intisar", "Rihab", "Aida", "Nahla", "Raghda", "Riham", "Majida", "Ahlam"],
      last_names: ["Al-Mazrui", "Al-Busaidi", "Al-Hinai", "Al-Kharusi", "Al-Hassani", "Al-Farsi", "Al-Habsi", "Al-Balushi", "Al-Riyami", "Al-Maamari", "Al-Harrasi", "Al-Rawahi", "Al-Amri", "Al-Hatmi", "Al-Saadi", "Al-Hajri", "Al-Maashani", "Al-Sabahi", "Al-Salti", "Al-Ghafri", "Al-Mashani", "Al-Tobi", "Al-Habsi", "Al-Balushi", "Al-Nabhani", "Al-Mahrouqi", "Al-Rasbi", "Al-Hinai", "Al-Rawahi", "Al-Abri", "Al-Ruqashi", "Al-Sarmi", "Al-Zadjali", "Al-Mamari", "Al-Jabri", "Al-Kharusi", "Al-Farsi", "Al-Hashmi", "Al-Saidi", "Al-Nahdi", "Al-Shezawi", "Al-Masoudi", "Al-Mahri", "Al-Kiyumi", "Al-Malki", "Al-Kharusi", "Al-Hajri", "Al-Siyabi", "Al-Tobi", "Al-Zadjali", "Al-Wahaibi", "Al-Salti", "Al-Ghassani", "Al-Harrasi", "Al-Maawali", "Al-Riyami", "Al-Maamari", "Al-Saadi", "Al-Nabhani", "Al-Ruqashi", "Al-Sarmi", "Al-Hilali", "Al-Hashmi", "Al-Shezawi", "Al-Masoudi", "Al-Mahri", "Al-Kiyumi", "Al-Malki", "Al-Nahdi", "Al-Kharusi", "Al-Siyabi", "Al-Tobi", "Al-Saadi", "Al-Ghassani", "Al-Maawali", "Al-Riyami", "Al-Nabhani", "Al-Ruqashi", "Al-Sarmi", "Al-Hilali"]
    },
  
    arabic: {
      male: ["Ahmed", "Mohammed", "Omar", "Ali", "Youssef", "Khalid", "Tariq", "Hassan", "Majed", "Fahad", "Sami", "Nasser", "Abdullah", "Hussein", "Adel", "Waleed", "Mamdouh", "Amr", "Rami", "Mahmoud", "Tamer", "Salem", "Karim", "Jihad", "Ibrahim", "Fadi", "Yasin", "Riad", "Faisal", "Nabil", "Kareem", "Rafik", "Mustafa", "Jamal", "Hamza", "Naji", "Munir", "Fares", "Zakaria", "Jawad", "Said", "Aziz", "Jaber", "Bilal", "Mansour", "Rashid", "Nizar", "Saif", "Nidal", "Hadi", "Nawaf", "Jassim", "Othman", "Hisham", "Hazem", "Sulaiman", "Anwar", "Ammar", "Nader", "Kamal", "Ismail", "Saeed", "Samir", "Ziad", "Taher", "Atef", "Qasim", "Abdel", "Badr", "Hisham", "Mohsin", "Naji", "Nahed", "Rustom", "Saad", "Tawfiq", "Usama", "Wahid", "Yazan", "Zuhair", "Adnan", "Bassam", "Daoud", "Emad", "Farid", "Ghazi", "Hakim", "Ismet", "Jamil"],
      female: ["Fatima", "Amina", "Leila", "Nour", "Hana", "Layla", "Zahra", "Rana", "Dana", "Sara", "Jana", "Yara", "Lina", "Amal", "Maya", "Rima", "Nada", "Maha", "Samar", "Aya", "Zeinab", "Mona", "Nadia", "Hoda", "Rasha", "Salma", "Ghada", "Najla", "Wafa", "Hanan", "Hoda", "Basma", "Dalia", "Lamia", "Riham", "Hala", "Maysa", "Safia", "Farida", "Shaima", "Nisreen", "Hayat", "Asma", "Lubna", "Rabab", "Ibtisam", "Nawal", "Habiba", "Afaf", "Rafif", "Soraya", "Ferial", "Abeer", "Nahla", "Sana", "Rola", "Fayza", "Siham", "Widad", "Hanan", "Fadia", "Sabah", "Rabia", "Faten", "Hayfa", "Zainab", "Zain", "Khadija", "Asmahan", "Asil", "Noura", "Hawraa", "Amira", "Joumana", "Kawthar", "Lamis", "Mouna", "Nashwa", "Nouf", "Sahar", "Shaza", "Warda", "Yasmin", "Zainab"],
      last_names: ["Al-Mansoor", "Al-Rashid", "Al-Hariri", "Al-Masri", "Al-Sabbagh", "Al-Khatib", "Al-Farsi", "Al-Abboud", "Al-Zarif", "Al-Qassem", "Al-Hakim", "Al-Abdullah", "Al-Maari", "Al-Fahd", "Al-Saleh", "Al-Najjar", "Al-Daher", "Al-Malik", "Al-Badawi", "Al-Moussa", "Al-Zoubi", "Al-Bassam", "Al-Talib", "Al-Khalaf", "Al-Dagher", "Al-Saadi", "Al-Zahrani", "Al-Attar", "Al-Jabari", "Al-Karimi", "Al-Nouri", "Al-Mashhadi", "Al-Sharif", "Al-Awad", "Al-Mansour", "Al-Qudsi", "Al-Mawla", "Al-Roumi", "Al-Khaldi", "Al-Maamari", "Al-Turk", "Al-Jishi", "Al-Batal", "Al-Saad", "Al-Rawi", "Al-Mahmoud", "Al-Sultan", "Al-Mousa", "Al-Kazemi", "Al-Aziz", "Al-Khateeb", "Al-Salman", "Al-Hadi", "Al-Tabari", "Al-Qureshi", "Al-Shami", "Al-Naser", "Al-Rahman", "Al-Rikabi", "Al-Khayyat", "Al-Badr", "Al-Ashraf", "Al-Ghazi", "Al-Samarra'i", "Al-Husaini", "Al-Khayyam", "Al-Zubaidi", "Al-Jibouri", "Al-Naimi", "Al-Baath", "Al-Farouk", "Al-Jazairi", "Al-Harbi", "Al-Taji", "Al-Murad", "Al-Hamidi", "Al-Masoud", "Al-Maqqari", "Al-Farsi", "Al-Zaidi", "Al-Moussawi", "Al-Husseini"]
    },
  
    vanuatu: {
      male: ["Manu", "Isei", "Joses", "Liamu", "Tomas", "Solomon", "John", "Iolu", "Esava", "Philip", "James", "George", "Junior", "Moses", "Andrew", "Viliamu", "Napuati", "Kalo", "Nemson", "Elton", "Michael", "Kemuel", "Steven", "Joseph", "Nixon", "Leon", "Vincent", "Harry", "Charlie", "Julian", "Edmond", "Albert", "Isaac", "Peter", "Jason", "Robert", "Daniel", "Edward", "Matthew", "Henry", "Jerry", "Ralph", "Frank", "Patrick", "Samuel", "William", "Anthony", "Clifford", "Reginald", "Timothy", "Nicholas", "Gilbert", "Benjamin", "Raymond", "Frederick", "Gavin", "Raynold", "Paul", "David", "Richard", "Jonathan", "Ricky", "Noel", "Fred", "Ronald", "Brian", "Gideon", "Gabriel", "Simon", "Roger", "Dominic", "Terry", "Charles", "Oliver", "Kalsakau", "Kaua", "Niku", "Obed", "Shem", "Selwin", "Jame", "Issac", "Leslie", "Ronny", "Ian", "Kolinio", "Kemuel", "Kensi", "Tony", "Tanna", "Kalmet", "Marcel", "Keret", "Nalton"],
      female: ["Mary", "Selina", "Linda", "Grace", "Nancy", "Lillian", "Anna", "Jane", "Irene", "Eileen", "Jill", "Judith", "Rosa", "Sophie", "Julia", "Dorothy", "Iris", "Joyce", "Marie", "Margaret", "Rebecca", "Helen", "Elsie", "Emily", "Fiona", "Lisa", "Katherine", "Tessie", "Daisy", "Vanessa", "Lavenia", "Lisimat", "Julianne", "Jean", "Penina", "Stephanie", "Serah", "Claire", "Louise", "Rachel", "Yvonne", "Alice", "Beatrice", "Esther", "Pauline", "Chantal", "Ruth", "Vilimaine", "Annie", "Betty", "Flora", "Phyllis", "Faye", "Frances", "Cathy", "Bella", "Deborah", "Jennifer", "Cynthia", "Sandra", "Wendy", "Victoria", "Miriam", "Melissa", "Nina", "Pamela", "Heather", "Denise", "Gloria", "Violet", "Tiffany", "Amanda", "Jessica", "Nicole", "Crystal", "Stephanie", "Kylie", "Natalie", "Megan", "Samantha", "Brittany", "Ashley", "Chelsea", "Emily", "Hannah", "Lauren", "Taylor"],
      last_names: ["Iati", "Kalsakau", "Lini", "Kemakeza", "Kilman", "Natuman", "Sahe", "Tete", "Ati", "Bule", "Tom", "Kalo", "Kalo", "Kalontin", "Natapei", "Charley", "Samson", "Jimmy", "George", "Iamo", "Lassal", "Bani", "Kalsera", "Vera", "John", "Kasel", "Meltenoven", "Daniel", "Mateariki", "Molisa", "Kalman", "Nikiau", "Kalorib", "Kanari", "Nikau", "Kanake", "Karitina", "Kasum", "Vikary", "Kasius", "Daniel", "Kasune", "Vanuaroroa", "Kasvir", "Marai", "Kaswokwok", "Tom", "Kaswokwok", "Marcelin", "Kawia", "Niko", "Kawo", "Nikiau", "Kawor", "Nepuati", "Kawor", "Nikiau", "Kawor", "Nepuati", "Kawor", "Niko", "Kawor", "Nikiau", "Kawor", "Nepuati", "Kayser", "Marcelin", "Kesai", "Kalorib", "Kesment", "James", "Kesua", "Kembong", "Kesua", "Kalo", "Ketoa", "Marcelin", "Ketoa", "Marcelin", "Ketoa", "Nepuati", "Ketoa", "Nikiau", "Kilman", "Nikiau"]
    },
  
    ireland: {
      male: ["Sean", "Conor", "Cillian", "Liam", "Finn", "Patrick", "Darragh", "Cian", "Eoin", "Niall", "Rory", "Tadhg", "Oisin", "Ciaran", "Cormac", "Declan", "Padraig", "Fergus", "Cathal", "Diarmuid", "Ruairi", "Odhran", "Donal", "Eamon", "Colm", "Killian", "Malachy", "Peadar", "Ciaran", "Caoimhin", "Senan", "Cillian", "Lorcan", "Tiarnan", "Enda", "Dara", "Seamus", "Garrett", "Gearoid", "Shane", "Blaine", "Eoghan", "Cathal", "Caolan", "Ollie", "Eanna", "Art", "Oscar", "Cormac", "Ruaidhri", "Seanie", "Lorcan", "Ronan", "Sean Og", "Tomas", "Padraic", "Eanna", "Donnacha", "Brendan", "Desmond", "Eamonn", "Colum", "Dermot", "Finbar", "Naoise", "Cianan", "Fiachra", "Fionn", "Jarlath", "Lorcan", "Padraigin", "Ruairi", "Tiarnach", "Tomas", "Ultan", "Fergal", "Eanna", "Colum", "Aodhan", "Darragh", "Padraig", "Ruadhan", "Fionn", "Felim", "Diarmaid", "Conall", "Derry", "Micheal", "Sean", "Eoin"],
      female: ["Aoife", "Caoimhe", "Roisin", "Niamh", "Saoirse", "Eabha", "Ciara", "Orla", "Aisling", "Fiona", "Maeve", "Grainne", "Sinead", "Eimear", "Aine", "Brigid", "Aoibheann", "Nuala", "Fionnuala", "Caitriona", "Sorcha", "Mairead", "Clodagh", "Muireann", "Deirdre", "Siobhan", "Nessa", "Ailbhe", "Siun", "Eithne", "Aoibhinn", "Aine", "Laoise", "Aoibhe", "Blathnaid", "Caitlin", "Maire", "Doireann", "Meabh", "Fidelma", "Sibeal", "Gobnait", "Cionnaith", "Sorcha", "Eadaoin", "Maireann", "Cliodhna", "Oonagh", "Treasa", "Naoise", "Padraigin", "Siobhra", "Laoise", "Sorcha", "Fionnuala", "Roise", "Nuala", "Saorla", "Riona", "Eimear", "Ailish", "Treasa", "Mairead", "Fionnuala", "Aibhilin", "Lasairfhiona", "Eilis", "Siomha", "Eithne", "Doireann", "Orlagh", "Siobhan", "Mealla", "Muireann", "Muirgheal", "Iseult", "Orlaith", "Dearbhail", "Aodhamair", "Dervla", "Liadan", "Daimhin", "Colleen", "Sorcha", "Fainche", "Bronagh", "Saorla", "Trea"],
      last_names: ["Murphy", "Kelly", "O'Sullivan", "Walsh", "Smith", "O'Brien", "Byrne", "Ryan", "O'Connor", "O'Neill", "O'Reilly", "Doyle", "McCarthy", "Gallagher", "Doherty", "Kennedy", "Lynch", "Murray", "Quinn", "Moore", "McDonagh", "Hogan", "Molloy", "Lyons", "Brady", "Foley", "Fitzpatrick", "Hayes", "Duffy", "McNamara", "Brennan", "Bourke", "Daly", "McGuire", "Dolan", "Conway", "Collins", "Kavanagh", "Clarke", "Carroll", "Connelly", "Fitzgerald", "Malone", "Griffin", "Nolan", "Reilly", "Higgins", "Flynn", "Cunningham", "Sheehan", "Magee", "O'Mahony", "Barry", "Cassidy", "Brennan", "Power", "Walsh", "Ward", "Hughes", "Roche", "Farrell", "Nash", "McMahon", "Fleming", "Keane", "Cahill", "Gleeson", "Dermody", "Fagan", "Hurley", "Rourke", "Bolger", "Cronin", "Deegan", "Condon", "Harte", "MacMahon", "McGrath", "Nolan", "O'Doherty", "O'Keeffe", "O'Reilly", "O'Shea", "Phelan", "Shannon", "Sweeney", "White", "Woods"]
    },
  
    india: {
      male: ["Aarav", "Aryan", "Rohan", "Kiran", "Vishal", "Akshay", "Raj", "Rahul", "Siddharth", "Arjun", "Aditya", "Ravi", "Aniket", "Pranav", "Varun", "Shubham", "Nikhil", "Amit", "Rishabh", "Harsh", "Parth", "Saurabh", "Kunal", "Alok", "Vivek", "Vinay", "Anuj", "Gaurav", "Amitabh", "Ankit", "Ritesh", "Vikram", "Sandeep", "Rajesh", "Manoj", "Arun", "Nitin", "Sanjay", "Deepak", "Vijay", "Rajat", "Avinash", "Pankaj", "Rohit", "Hitesh", "Sachin", "Ranjeet", "Sushant", "Yash", "Pradeep", "Ganesh", "Shashank", "Rajiv", "Amar", "Ashish", "Karthik", "Naveen", "Abhishek", "Deepesh", "Vikas", "Sunil", "Nishant", "Shivam", "Dinesh", "Manish", "Raman", "Anand", "Avinash", "Nikhil", "Ashok", "Arun", "Vinod", "Praveen", "Rajendra", "Dheeraj", "Anil", "Devendra", "Santosh", "Vikrant", "Yogesh", "Rajeev", "Rakesh", "Subhash", "Gopal", "Rahul", "Ashutosh", "Mayank", "Arun", "Suresh", "Girish", "Rahul"],
      female: ["Aisha", "Ananya", "Ishita", "Kavya", "Neha", "Pooja", "Riya", "Sanya", "Aaradhya", "Avani", "Ishani", "Tanya", "Radhika", "Meera", "Tanvi", "Aishwarya", "Swara", "Aditi", "Aanya", "Anushka", "Divya", "Nisha", "Simran", "Trisha", "Yamini", "Khushi", "Vidhi", "Sakshi", "Sneha", "Anjali", "Juhi", "Priya", "Prisha", "Siya", "Kritika", "Shreya", "Ritika", "Akanksha", "Vaishnavi", "Pari", "Muskan", "Shivani", "Aashi", "Aradhya", "Rupal", "Nidhi", "Naina", "Roshni", "Preeti", "Shubhi", "Kirti", "Tanisha", "Aarohi", "Manvi", "Isha", "Jyoti", "Aanya", "Adhya", "Palak", "Aarushi", "Mansi", "Sonam", "Vandana", "Madhu", "Priyanka", "Renuka", "Rekha", "Suman", "Uma", "Sheetal", "Kusum", "Alka", "Meenakshi", "Rukmini", "Aarti", "Anjana", "Geeta", "Sarita", "Indira", "Jaya", "Kiran", "Leela", "Malini", "Radha", "Rani", "Savitri", "Urmila"],
      last_names: ["Patel", "Sharma", "Verma", "Singh", "Yadav", "Jha", "Reddy", "Kumar", "Nair", "Nayak", "Bose", "Das", "Mukherjee", "Rao", "Gupta", "Choudhury", "Sinha", "Malik", "Roy", "Mehta", "Saxena", "Chauhan", "Thakur", "Rathod", "Rajput", "Dutta", "Chakraborty", "Pandey", "Bhat", "Shah", "Yadav", "Acharya", "Shukla", "Mishra", "Sharma", "Jain", "Agarwal", "Varma", "Dubey", "Sharma", "Jha", "Goswami", "Trivedi", "Tiwari", "Lal", "Yadav", "Bajaj", "Chopra", "Ahuja", "Khanna", "Gulati", "Dewan", "Kapoor", "Mehra", "Chopra", "Arora", "Suri", "Nanda", "Khatri", "Sethi", "Sareen", "Mittal", "Bhasin", "Bali", "Dhillon", "Narang", "Anand", "Chadha", "Taneja", "Chawla", "Kohli", "Wadhwa", "Datta", "Soni", "Kaul", "Gill", "Seth", "Beri", "Khurana", "Vohra", "Verma", "Mathur", "Oberoi"]
    },
  
    estonia: {
      male: ["Jaan", "Kristjan", "Andres", "Marko", "Mihkel", "Mart", "Rasmus", "Hannes", "Karl", "Taavi", "Tõnis", "Jüri", "Siim", "Erki", "Andero", "Raul", "Henrik", "Rein", "Lauri", "Sander", "Marten", "Mairo", "Tanel", "Madis", "Ahti", "Johannes", "Jarmo", "Peeter", "Märt", "Rivo", "Urmas", "Priit", "Kaur", "Kaspar", "Risto", "Toomas", "Aivar", "Vahur", "Rain", "Kristo", "Oliver", "Veiko", "Erik", "Kalju", "Kardo", "Kaido", "Roland", "Eduard", "Henno", "Oskar", "Ants", "Alo", "Janno", "Evald", "Hardi", "Ivo", "Raivo", "Kaupo", "Mardo", "Külli", "Viljar", "Ivar", "Hendrik", "Margus", "Tarmo", "Tarvo", "Meelis", "Arvo", "Kalev", "Andrus", "Rene", "Arno", "Elar", "Joonas", "Ervin", "Väino", "Egert", "Raimo", "Karl-Gustav", "Vallo", "Villem", "Voldemar", "Mihhail", "Koit", "Helari", "Jürgen", "Alar"],
      female: ["Mari", "Laura", "Kadri", "Liis", "Maret", "Anu", "Eva", "Piret", "Helena", "Kersti", "Ave", "Sirje", "Mairi", "Katrin", "Triin", "Annika", "Kairi", "Liina", "Kristiina", "Ingrid", "Evelin", "Eleri", "Maarja", "Merike", "Karoliina", "Silja", "Diana", "Margit", "Triinu", "Kadri-Ann", "Tiina", "Kadi", "Maie", "Tiiu", "Eha", "Hanna", "Anna", "Krista", "Riina", "Liisa", "Marika", "Kärt", "Greete", "Jana", "Janika", "Daisy", "Sandra", "Heleri", "Hanna-Liisa", "Kätlin", "Laine", "Kerli", "Eliise", "Anneli", "Eve", "Reelika", "Helis", "Johanna", "Mia", "Karina", "Annela", "Liisbet", "Heidi", "Irina", "Marianne", "Diana", "Helin", "Berit", "Grete", "Signe", "Kärolin", "Kirsti", "Monika", "Mall", "Marge", "Ketlin", "Riin", "Kristina", "Triine", "Grete", "Helerin", "Ursula", "Marleen", "Katriin", "Greete", "Ragne", "Marit", "Karolin"],
      last_names: ["Tamm", "Mets", "Kask", "Oja", "Lepik", "Pärn", "Sild", "Laur", "Kuusk", "Saar", "Kivi", "Talve", "Rebane", "Kangur", "Allikas", "Tammeleht", "Ploom", "Raud", "Mägi", "Jürgens", "Valk", "Kallas", "Välja", "Aas", "Karro", "Uibo", "Paju", "Toom", "Teder", "Kelder", "Laas", "Mikk", "Eensaar", "Reinsoo", "Riim", "Kuuse", "Lõhmus", "Tuul", "Alamaa", "Uus", "Toomla", "Piir", "Tender", "Lomp", "Voika", "Lass", "Tolm", "Põld", "Järve", "Kald", "Kangro", "Vares", "Ojamäe", "Pukk", "Maripuu", "Kasemets", "Tilga", "Soome", "Lobjakas", "Järveoja", "Meister", "Hein", "Tilk", "Kaskla", "Pildre", "Lään", "Nõmm", "Ots", "Mandri", "Luik", "Teppo", "Lepaste", "Aavik", "Kiviorg", "Purje", "Soo", "Kukk", "Kink", "Vunk", "Masing", "Tammsaar", "Pärna", "Sulane", "Veeber", "Ülejõe"]
    },
  
    afghanistan: {
      male: ["Ahmad", "Mohammad", "Ali", "Hassan", "Hussein", "Abdullah", "Omar", "Sultan", "Mahmood", "Hamid", "Jawad", "Qasim", "Amin", "Rahim", "Zakir", "Khalid", "Wahid", "Karim", "Najib", "Farid", "Jamal", "Sami", "Said", "Ismail", "Yusuf", "Rashid", "Shafiq", "Fahim", "Latif", "Zia", "Rafi", "Ghulam", "Nasir", "Mustafa", "Dawood", "Arif", "Esmail", "Akbar", "Bilal", "Faisal", "Rafiullah", "Aziz", "Tariq", "Jalil", "Qadir", "Taj Mohammad", "Karimullah", "Saifullah", "Nawid", "Obaidullah", "Aryan", "Osman", "Bashir", "Wais", "Noor", "Obaid", "Ibrahim", "Ehsan", "Wali", "Shahid", "Mohsen", "Khan", "Asad", "Wahab", "Zubair", "Omid", "Sohail", "Hayatullah", "Elyas", "Mushtaq", "Arman", "Aryan", "Farhad", "Qais", "Zahir", "Nadir", "Hekmat", "Ramin", "Javed", "Akram", "Imran", "Kamran", "Feroz", "Rahmat", "Shoaib", "Omidullah", "Aminullah", "Zainullah", "Mirwais"],
      female: ["Fatima", "Maryam", "Aisha", "Zainab", "Safia", "Gulnaz", "Freshta", "Laila", "Parisa", "Nargis", "Rukhsar", "Shabnam", "Samira", "Nadia", "Shahla", "Nasrin", "Nahid", "Farida", "Zarina", "Mursal", "Malalai", "Marzia", "Zahra", "Soraya", "Leila", "Sima", "Latifa", "Fawzia", "Rahima", "Shaima", "Roqia", "Hosna", "Marjan", "Jamila", "Shukria", "Zeba", "Zohra", "Zubaida", "Halima", "Najiba", "Feroza", "Amina", "Zarghona", "Farzana", "Nooria", "Kawtar", "Amani", "Hooria", "Anisa", "Naima", "Shokria", "Bibi", "Shereen", "Zahida", "Gulalai", "Nadia", "Mahboba", "Sabiha", "Nigara", "Shahnaz", "Roshan", "Friba", "Mahsima", "Tahmina", "Palwasha", "Parween", "Fereshta", "Mahpara", "Samina", "Fahima", "Rozina", "Najia", "Safiya", "Tahira", "Soraya", "Faisal", "Marya", "Raziya", "Mahjabin", "Farahnaz", "Shela", "Lina", "Diba"],
      last_names: ["Ahmadi", "Khan", "Safi", "Jan", "Hakimi", "Habibi", "Omar", "Azizi", "Rahimi", "Yusufzai", "Popal", "Sidiqi", "Shirzai", "Ismail", "Kazimi", "Karimi", "Jafari", "Noori", "Wardak", "Sahibzada", "Mujahid", "Najibullah", "Amini", "Hashimi", "Haidari", "Jamshidi", "Mahmood", "Sultani", "Shafiq", "Nabi", "Qureshi", "Mohammadi", "Farid", "Qaderi", "Atal", "Osmani", "Ibrahimi", "Sayed", "Mansoor", "Sarwari", "Sayedzada", "Yousafzai", "Barakzai", "Yaqubi", "Omarzai", "Sadiqi", "Fahim", "Azim", "Zakir", "Osman", "Hassani", "Nawabi", "Arya", "Rasooli", "Daudzai", "Zadran", "Wali", "Latifi", "Ghani", "Qayoumi", "Ferozi", "Taraki", "Mohseni", "Zafari", "Kakar", "Sayed", "Zia", "Jawadi", "Esmat", "Sediqi", "Yama", "Mohib", "Popalzai", "Asad", "Khil", "Dawlatzai", "Sharif", "Tariq", "Zahid", "Wasiq", "Farooqi"]
    },
  
    lithuanian: {
      male: ["Jonas", "Antanas", "Tomas", "Lukas", "Matas", "Domantas", "Giedrius", "Mantas", "Karolis", "Povilas", "Eduardas", "Edgaras", "Justas", "Vytautas", "Darius", "Andrius", "Arnas", "Augustas", "Domas", "Emilis", "Ignas", "Kasparas", "Leonardas", "Mindaugas", "Nerijus", "Paulius", "Rokas", "Simonas", "Valdas", "Vaidotas", "Zigmas", "Žygimantas", "Aurimas", "Benas", "Eimantas", "Feliksas", "Gytis", "Haroldas", "Inas", "Jonatas", "Kęstutis", "Laurynas", "Marijus", "Nauris", "Oskaras", "Pranas", "Ričardas", "Saulius", "Teodoras", "Ugnius", "Vytas", "Žilvinas", "Aidas", "Balys", "Česlovas", "Dainius", "Eligijus", "Fridrikas", "Gintaras", "Henrikas", "Ignotas", "Juozapas", "Kajus", "Leonas", "Modestas", "Naktis", "Ovidijus", "Petrus", "Rimas", "Silvestras", "Titas", "Urbanas", "Vincas", "Zenonas", "Žavinta", "Aelita", "Bernadeta", "Dorotėja", "Elena", "Feliksa", "Gabija", "Ieva", "Jolanta", "Karolina", "Laima", "Margarita", "Nijolė", "Ona", "Patricija", "Ramunė", "Salomėja", "Toma", "Ugnė", "Viktorija", "Zita", "Austėja", "Brigita", "Česlava", "Daiva", "Eglė"],
      female: ["Jurgita", "Rūpinta", "Živilė", "Kotryna", "Edita", "Dovilė", "Kristina", "Viktorija", "Ieva", "Greta", "Laura", "Simona", "Lina", "Gabija", "Eglė", "Jolanta", "Miglė", "Inga", "Rasa", "Rūpinta", "Laimutė", "Asta", "Agnė", "Renata", "Sigita", "Jūratė", "Giedrė", "Akvilė", "Dalia", "Aldona", "Zita", "Indrė", "Gražina", "Milda", "Vilma", "Aelita", "Vaida", "Viltė", "Kornelija", "Emilija", "Asta", "Viktorija", "Vitalija", "Ramunė", "Laima", "Inesa", "Živilė", "Diana", "Monika", "Neringa", "Vesta", "Rūpinta", "Justina", "Aušra", "Natalija", "Goda", "Saule", "Ema", "Barbora", "Jūratė", "Brigita", "Ieva", "Deimantė", "Dalia", "Žydrūnė", "Akvilė", "Dalia", "Rita", "Vaida", "Austeja", "Silvija", "Milda", "Laura", "Ona", "Kamile", "Agne", "Lina", "Rūpinta", "Vaida", "Julija", "Gabrielė", "Gintarė", "Diana", "Vita", "Margarita", "Greta", "Viktorija", "Asta", "Ieva", "Jūratė", "Rūpinta", "Indrė", "Kotryna", "Rasa", "Gražina", "Zofija"],
      last_names: ["Kazlauskas", "Petrauskas", "Jankauskas", "Lukauskas", "Butkus", "Kavaliauskas", "Stankevičius", "Vaitkus", "Kulikauskas", "Sakalauskas", "Mickus", "Gedminas", "Ulevičius", "Zubrus", "Čeponis", "Šeškas", "Lukšys", "Petrulis", "Vilkas", "Girdenis", "Valys", "Baltušis", "Brazauskas", "Gudaitis", "Giraitis", "Pocius", "Narbutas", "Bartkus", "Budrys", "Žemaitis", "Jurgaitis", "Mazėnas", "Vingras", "Žižys", "Gulbinas", "Česnulis", "Macevičius", "Morkūnas", "Pranaitis", "Juška", "Dailidė", "Dainius", "Fainas", "Kerbedis", "Stonys", "Žvirblis", "Rimkus", "Žalpys", "Grigaitis", "Puskunigis", "Dargis", "Baužys", "Vitkus", "Balčiūnas", "Vidmantas", "Zaleckis", "Drunga", "Valavicius", "Zaleckis", "Jurkša", "Džiaugys", "Vingras", "Šaltenis", "Barauskas", "Sadauskas", "Budrys", "Pundzius", "Sėjūnas", "Noreika", "Paliulis", "Gudelis", "Raugala", "Skripka", "Zupkauskas", "Kalpokas", "Gricius", "Stasiūnas", "Ramanauskas", "Mikėnas", "Paltarokas", "Saulėnas", "Pundzius", "Grigonis", "Vasiliauskas", "Čižas", "Česnulis", "Makštutis"]
    },
  
    iraq: {
      male: ["Ali", "Mohammed", "Hassan", "Omar", "Ahmed", "Abdullah", "Jawad", "Majid", "Khalid", "Saad", "Ameer", "Zaid", "Karim", "Yousef", "Qasim", "Mahmoud", "Hussein", "Tariq", "Mustafa", "Raed", "Nabil", "Laith", "Nasir", "Mazen", "Firas", "Kadhim", "Ammar", "Sami", "Fahad", "Tamer", "Nizar", "Ibrahim", "Ammar", "Kamal", "Haidar", "Waleed", "Sarmad", "Muthanna", "Luay", "Amer", "Riyadh", "Thaer", "Yaser", "Wadah", "Jasim", "Qusay", "Salah", "Yahya", "Fadi", "Bilal", "Ammar", "Aziz", "Ali", "Hadi", "Sadiq", "Awni", "Muhannad", "Jafar", "Talal", "Kareem", "Ahmad", "Ayman", "Marwan", "Abbas", "Naji", "Saif", "Imad", "Wael", "Jalal", "Faris", "Haydar", "Riad", "Haider", "Taher", "Tawfiq", "Hisham", "Qais", "Nihad", "Arkan", "Taha", "Adnan", "Kazem", "Fadel", "Asaad", "Zakariya", "Shaker", "Mowaffaq"],
      female: ["Fatima", "Zainab", "Amina", "Maryam", "Layla", "Noor", "Sara", "Hana", "Aisha", "Rana", "Shayma", "Zahra", "Nadia", "Maya", "Leen", "Noura", "Dalal", "Farah", "Huda", "Raghad", "Zaynab", "Rasha", "Batoul", "Lina", "Samira", "Asma", "Hanan", "Dina", "Najla", "Muna", "Riham", "Samar", "Nawal", "Rabab", "Layan", "Wafa", "Reem", "Faten", "Fadia", "Maha", "Naima", "Lamis", "Hajar", "Lubna", "Basma", "Hayat", "Saja", "Bushra", "Rim", "Shaima", "Manal", "Ibtisam", "Sawsan", "Suha", "Suad", "Nisreen", "Habiba", "Afaf", "Jamila", "Sabah", "Hawra", "Maysa", "Maha", "Hind", "Suhair", "Warda", "Entisar", "Najah", "Amal", "Lamia", "Kawthar", "Lina", "Safia", "Shahad", "Mai", "Layla", "Fadila", "Nadia", "Nawal", "Rahma", "Asalah", "Hala", "Malak", "Salwa", "Zina", "Alia", "Abeer", "Safa", "Hayfa"],
      last_names: ["Al-Abadi", "Al-Amiri", "Al-Ani", "Al-Asadi", "Al-Badri", "Al-Baghdadi", "Al-Douri", "Al-Fayyad", "Al-Hakim", "Al-Hashimi", "Al-Hassani", "Al-Jabouri", "Al-Jaafari", "Al-Jubouri", "Al-Kadhimi", "Al-Karbala'i", "Al-Khafaji", "Al-Khazali", "Al-Maliki", "Al-Mansouri", "Al-Moussawi", "Al-Najjar", "Al-Nouri", "Al-Obeidi", "Al-Qahtani", "Al-Qaisi", "Al-Qassab", "Al-Rawi", "Al-Saadi", "Al-Sadr", "Al-Salman", "Al-Shammari", "Al-Sistani", "Al-Tikriti", "Al-Zaidi", "Al-Zarqawi", "Al-Zubaidi", "Al-Zurfi", "Alwan", "Atiyah", "Ghazali", "Hakim", "Hamza", "Hasan", "Ismail", "Jassem", "Kareem", "Kazem", "Khalaf", "Maarouf", "Mahmoud", "Majid", "Mansour", "Marzouq", "Mohammed", "Muhsin", "Murtadha", "Najm", "Nasir", "Qasim", "Quraishi", "Ridha", "Saad", "Sabri", "Sadiq", "Salim", "Samarrai", "Sattar", "Shihab", "Suhail", "Talib", "Tawfiq", "Thamer", "Wahab", "Yahya", "Zaki", "Zubair"]
    },
  
    turkey: {
      male: ["Emir", "Eren", "Can", "Deniz", "Arda", "Berk", "Kaan", "Ali", "Mert", "Yusuf", "Ozan", "Kerem", "Tolga", "Cem", "Ata", "Burak", "Umut", "Ege", "Serkan", "Baran", "Onur", "Mert", "Hakan", "Furkan", "Utku", "Oğuz", "Enes", "Ege", "Alp", "Efe", "Ayhan", "Murat", "Batuhan", "Yiğit", "Cihan", "Gökhan", "Caner", "Fikret", "Berke", "Kaya", "Sarp", "Erdem", "Okan", "Aslan", "Ozan", "Tuncay", "Ahmet", "Taha", "Selim", "Erhan", "Sinan", "Tolunay", "Ercan", "Yavuz", "Eray", "Kutay", "Orhan", "Oktay", "Mehmet", "Emre", "Rüzgar", "Yalın", "Soner", "Cemal", "Serkan", "Deniz", "Cenk", "Gürkan", "Olgun", "Tarkan", "Kürşad", "Emrah", "Kemal", "Hüseyin", "Emin", "Halis", "Ogün", "Fatih", "Talha", "Levent", "Muhammed", "Mustafa", "Orkun", "Cemil", "Arif"],
      female: ["Elif", "Zeynep", "Ceren", "Melis", "Ayşe", "Defne", "Ece", "Selin", "Naz", "İrem", "Damla", "Irmak", "Büşra", "Deniz", "Esra", "Gizem", "Derya", "Aysu", "Elçin", "İdil", "Merve", "Nisan", "Nehir", "Yaren", "Yağmur", "Buse", "Simge", "Aslı", "Ezgi", "Asuman", "Zara", "Alara", "Serra", "Eylül", "Arzu", "İlayda", "Aylin", "Beren", "Gözde", "Cansu", "Ebru", "Nur", "Gamze", "Bengü", "Cemre", "Tuba", "Ezgi", "Seray", "Oya", "Burcu", "Leyla", "İlay", "Zehra", "Rabia", "Gül", "Sude", "Ecem", "Berfin", "Özge", "Beyza", "Ilgın", "Gizem", "Zümra", "Selma", "İlayda", "Sude", "Yasmin", "Rüya", "Bilge", "Dilara", "Tansu", "Sila", "İlknur", "Rana", "Gizem", "Arife", "Cemile", "Ayda", "Lara", "Gökcen", "Rabia", "Havva", "Binnur", "Duygu", "Fulya", "Yelda"],
      last_names: ["Yılmaz", "Kaya", "Demir", "Öztürk", "Yıldız", "Çelik", "Yalın", "Arslan", "Şahin", "Erdoğan", "Güneş", "Aktaş", "Koç", "Kurt", "Aydın", "Ateş", "Doğan", "Türk", "Eren", "Alp", "Oflaz", "Şimşek", "Çetin", "Taş", "Aksoy", "Özkan", "Yıldırım", "Karadağ", "Özdemir", "Tekin", "Şen", "Demirci", "Karakaş", "Kurtuluş", "Gür", "Kurtul", "Akgün", "Erenler", "Kurtuluş", "Özen", "Gürler", "Er", "Tosun", "Koçak", "Köse", "Akman", "Gök", "Çakır", "Türkmen", "Özgür", "İşler", "Türkoğlu", "Yaman", "Göktürk", "Akbaş", "Durmaz", "Şeker", "Toprak", "Türkay", "Karagöz", "Yaman", "Akın", "Güzel", "Karakaya", "Güzel", "Yüksel", "Bozkurt", "Güzel", "Acar", "Büyükkaya", "Karahan", "Bayram", "Arı", "Şentürk", "Oğuz", "Gül", "Öz", "Alkan", "Çakmak", "Özen", "Akbulut", "Sevinç", "Karaman", "Şahin", "Şenel"]
    },
  
    egypt: {
      male: ["Ahmed", "Mohamed", "Ali", "Omar", "Hassan", "Mahmoud", "Khaled", "Tarek", "Amr", "Youssef", "Karim", "Mohammed", "Ibrahim", "Hesham", "Adham", "Sherif", "Essam", "Ayman", "Samir", "Ahmed", "Nasser", "Saad", "Mohsen", "Tamer", "Emad", "Ashraf", "Maged", "Hamdy", "Moustafa", "Raafat", "Hani", "Hossam", "Fathy", "Hany", "Magdy", "Mokhtar", "Kamal", "Osama", "Nabil", "Nagib", "Walid", "Wael", "Adel", "Amr", "Tamer", "Hazem", "Ezzat", "Mamdouh", "Yahia", "Shawky", "Samy", "Hisham", "Ramzy", "Ashraf", "Khalid", "Salah", "Fouad", "Sayed", "Fawzy", "Ramy", "Ismail", "Hussein", "Faisal", "Gaber", "Makram", "Yahya", "Sobhy", "Habib", "Salim", "Abdallah", "Rafik", "Ragab", "Atef", "Morsi", "Sameh", "Eid", "Sami", "Farid", "Ezz", "Saber", "Rashad", "Nagy", "Mohsen", "Fathi", "Nour", "Hamada", "Hafez"],
      female: ["Nour", "Hana", "Yasmine", "Fatma", "Salma", "Sarah", "Aya", "Laila", "Mona", "Soha", "Nada", "Rania", "Samar", "Dina", "Asmaa", "Heba", "Reham", "Mai", "Naglaa", "Ghada", "Ola", "Omnia", "Nadia", "Amina", "Yara", "Farida", "Eman", "Zeinab", "Abeer", "Marwa", "Alia", "Shaimaa", "Hend", "Dalia", "Nadia", "Sherine", "Shereen", "Nihal", "Nelly", "Rasha", "Sally", "Nermeen", "Yomna", "Sahar", "Magda", "Hagar", "Lina", "Basma", "Wafaa", "Maya", "Hayam", "Hoda", "Doha", "Tahani", "Amani", "Amira", "Mervat", "Sabah", "Sanaa", "Tasneem", "Ebtisam", "Nehal", "Rabab", "Rafah", "Lamia", "Fadia", "Sawsan", "Riham", "Azza", "Aida", "Hanadi", "Latifa", "Lamis", "Amany", "Safia", "Nisreen", "Nahla", "Nihal", "Hayat", "Amal", "Fayza", "Hosnia", "Mona", "Rawia"],
      last_names: ["Mohamed", "Ali", "Ibrahim", "Abdelaziz", "Mahmoud", "Hassan", "Elshazly", "Elbanna", "Khalil", "Salem", "Elkhouly", "Elsayed", "Abdallah", "Shawky", "Tawfik", "Hegazy", "Naguib", "Khalifa", "Osman", "Elgohary", "Elrefai", "Ragab", "Eladl", "Eltaher", "Abdelhamid", "Elgammal", "Talaat", "Elbendary", "Abdelnaby", "Elabbasy", "Elnagar", "Sadek", "Eid", "Elsergany", "Elmasry", "Elhalwagy", "Elshemy", "Elkady", "Elhosary", "Elbadry", "Elfouly", "Elkafrawy", "Elmessiry", "Elrashidy", "Elkady", "Elrafie", "Elnaggar", "Abdelfattah", "Elhennawy", "Eladawy", "Elsharqawy", "Elmalt", "Abdelfattah", "Elshamy", "Elnahas", "Elbassuny", "Elmorsy", "Eltantawy", "Elnaggar", "Elnahrawy", "Abdelrazek", "Abdelhalim", "Elsherbiny", "Elbaz", "Elsamadony", "Elbahrawy", "Elnazer", "Elshawarby", "Elmenshawy", "Elsamadisy", "Elrafie", "Elhawary", "Eldemellawy", "Eltohamy", "Elzanaty", "Abdelazeem", "Elattar", "Elreedy", "Elrashidy", "Eltoukhy", "Elwakil"]
    },
  
    ghana: {
      male: ["Kwame", "Kofi", "Kwesi", "Kwabena", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama", "Kwaku", "Ato", "Kwadwo", "Kwasi", "Kobby", "Kwabena", "Osei", "Kwamina", "Kofi", "Kwame", "Ato", "Yaw", "Kojo", "Kwesi", "Kwabena", "Kwaku", "Kobby", "Kwame", "Kwesi", "Kwabena", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama", "Kwaku", "Ato", "Kwadwo", "Kwasi", "Kobby", "Kwabena", "Osei", "Kwamina", "Kofi", "Kwame", "Ato", "Yaw", "Kojo", "Kwesi", "Kwabena", "Kwaku", "Kobby", "Kwame", "Kwesi", "Kwabena", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama", "Kwaku", "Ato", "Kwadwo", "Kwasi", "Kobby", "Kwabena", "Osei", "Kwamina", "Kofi", "Kwame", "Ato", "Yaw", "Kojo", "Kwesi", "Kwabena", "Kwaku", "Kobby", "Kwame", "Kwesi", "Kwabena", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama"],
      female: ["Akua", "Afia", "Ama", "Adwoa", "Abena", "Akosua", "Aisha", "Akos", "Esi", "Amina", "Aku", "Ama", "Adwoa", "Akua", "Afia", "Ama", "Adwoa", "Abena", "Akosua", "Aisha", "Akos", "Esi", "Amina", "Aku", "Ama", "Adwoa", "Akua", "Afia", "Ama", "Adwoa", "Abena", "Akosua", "Aisha", "Akos", "Esi", "Amina", "Aku", "Ama", "Adwoa", "Akua", "Afia", "Ama", "Adwoa", "Abena", "Akosua", "Aisha", "Akos", "Esi", "Amina", "Aku", "Ama", "Adwoa", "Akua", "Afia", "Ama", "Adwoa", "Abena", "Akosua", "Aisha", "Akos", "Esi", "Amina", "Aku", "Ama", "Adwoa", "Akua", "Afia", "Ama", "Adwoa", "Abena", "Akosua", "Aisha", "Akos", "Esi", "Amina", "Aku", "Ama", "Adwoa", "Akua", "Afia", "Ama"],
      last_names: ["Appiah", "Adu", "Adom", "Mensah", "Owusu", "Asante", "Boateng", "Kwakye", "Amoako", "Darko", "Addo", "Acheampong", "Agyemang", "Osei", "Asamoah", "Antwi", "Adu", "Appiah", "Boadi", "Gyan", "Ababio", "Annan", "Dankwa", "Agyei", "Abdul", "Kwabena", "Kofi", "Kwesi", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama", "Kwaku", "Ato", "Kwadwo", "Kwasi", "Kobby", "Kwabena", "Osei", "Kwamina", "Kofi", "Kwame", "Ato", "Yaw", "Kojo", "Kwesi", "Kwabena", "Kwaku", "Kobby", "Kwame", "Kwesi", "Kwabena", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama", "Kwaku", "Ato", "Kwadwo", "Kwasi", "Kobby", "Kwabena", "Osei", "Kwamina", "Kofi", "Kwame", "Ato", "Yaw", "Kojo", "Kwesi", "Kwabena", "Kwaku", "Kobby", "Kwame", "Kwesi", "Kwabena", "Yaw", "Kojo", "Esi", "Akua", "Afia", "Ama"]
    },
  
    croatia: {
      male: ["Matej", "Ivan", "Luka", "Marko", "Petar", "Ante", "Toni", "Mario", "Josip", "Dario", "Filip", "Igor", "Nikola", "Ivano", "Renato", "Kristijan", "Dino", "Stjepan", "Tomislav", "Damir", "Šime", "Božo", "Marin", "Lovro", "Leo", "Karlo", "Bruno", "Dominik", "Denis", "Adrian", "Ilija", "Davor", "Dinko", "Goran", "Hrvoje", "Kruno", "Matija", "Nino", "Robert", "Saša", "Sinisa", "Tihomir", "Vanja", "Vedran", "Vlatko", "Zoran", "Zvonimir", "Alen", "Dalibor", "Darko", "Domagoj", "Drago", "Emil", "Franjo", "Grgur", "Ivica", "Jakov", "Jerko", "Jure", "Karlo", "Kristian", "Leon", "Lorenzo", "Mislav", "Nenad", "Pavao", "Roko", "Stipe", "Teo", "Tin", "Valentino", "Zdravko", "Željko", "Mato", "Antonio", "Benjamin", "Borna", "David", "Dorian", "Emanuel", "Fabijan", "Filip", "Gabriel", "Hrvoje", "Ivan", "Josip", "Karlo"],
      female: ["Ana", "Lucija", "Ema", "Petra", "Sara", "Lana", "Mia", "Iva", "Elena", "Martina", "Nika", "Dora", "Karla", "Katarina", "Lea", "Viktorija", "Anita", "Tamara", "Antonija", "Tea", "Monika", "Lorena", "Paula", "Marija", "Magdalena", "Maja", "Nina", "Helena", "Ivana", "Klara", "Marina", "Tina", "Vanessa", "Ela", "Ivona", "Josipa", "Lara", "Nela", "Valentina", "Adela", "Vanda", "Kornelija", "Ana-Marija", "Mihaela", "Matea", "Natalija", "Patricia", "Iris", "Antea", "Kristina", "Veronika", "Tamara", "Barbara", "Leona", "Brigita", "Dijana", "Elena", "Gabrijela", "Jana", "Jasmina", "Klaudija", "Linda", "Sandra", "Tamara", "Vlatka", "Dorotea", "Ivana", "Klara", "Lea", "Lorena", "Mia", "Nina", "Petra", "Sara", "Stela", "Tea", "Valentina", "Viktorija", "Ana", "Dora", "Ela", "Ema", "Helena", "Iris", "Karla", "Lara", "Lia", "Marta", "Matea", "Petra", "Sofia"],
      last_names: ["Horvat", "Kovačević", "Babić", "Kovač", "Novak", "Marić", "Jurić", "Knežević", "Vuković", "Ivanović", "Tomljanović", "Petrović", "Pavić", "Marković", "Kruljac", "Perić", "Šarić", "Kovačić", "Blažević", "Vidović", "Živković", "Šimunović", "Burić", "Baković", "Vidaković", "Jovanović", "Kovačev", "Pintarić", "Vidmar", "Kralj", "Knežić", "Mandić", "Ilić", "Lučić", "Tomić", "Žižić", "Barić", "Kasun", "Kos", "Stanić", "Čuljak", "Pavičić", "Krstić", "Blažić", "Rukavina", "Orešković", "Grgić", "Filić", "Prpić", "Bogdan", "Ferenčić", "Župan", "Šoštarić", "Blažeković", "Čop", "Žaja", "Grubišić", "Tadić", "Barbarić", "Lovrić", "Kolar", "Vujnović", "Kuzmanić", "Krešić", "Bakula", "Križanac", "Matošević", "Martinović", "Jovanov", "Bakarić", "Pavlić", "Čakarić", "Mikić", "Poljak", "Barun", "Furjan", "Pleša", "Delić", "Herceg", "Mihaljević", "Zadravec", "Vugrinec", "Marjanović", "Branilović"]
    },
  
    greece: {
      male: ["Nikos", "Yiannis", "Dimitris", "Giorgos", "Panos", "Christos", "Vasilis", "Michalis", "Thanos", "Kostas", "Takis", "Sakis", "Antonis", "Stavros", "Andreas", "Stelios", "Giannis", "Spiros", "Kostis", "Yorgos", "Angelos", "Thodoris", "Kostas", "Nikolas", "Petros", "Vaggelis", "Christoforos", "Haris", "Lefteris", "Apostolos", "Yannis", "Manolis", "Marinos", "Dimitrios", "Alexandros", "Giwrgos", "Leonidas", "Sotiris", "Aris", "Giannis", "Kostas", "Yiorgos", "Kyriakos", "Stratos", "Kimon", "Nikitas", "Nikos", "Antonis", "Ioannis", "Marios", "Michalis", "Theodoros", "Kostas", "Antonis", "Lazaros", "Giannis", "Alexandros", "Andreas", "Giannis", "Theo", "Yiorgos", "Pavlos", "Tasos", "Apostolis", "Dimitris", "Nikitas", "Sokratis", "Michail", "Iasonas", "Haris", "Kostis", "Giannis", "Vasilis", "Nikitas", "Nikos", "Konstantinos", "Nikos", "Panagiotis", "Giorgos", "Aris", "Antonis", "Dimitris", "Konstantinos", "Vaggelis", "Andreas", "Thanos", "Stathis", "Andreas", "Spyros", "Ilias"],
      female: ["Maria", "Eleni", "Sofia", "Despoina", "Vasiliki", "Katerina", "Anna", "Ioanna", "Paraskevi", "Christina", "Dimitra", "Nikoleta", "Eirini", "Aikaterini", "Angeliki", "Aikaterini", "Antigoni", "Alexandra", "Zoi", "Panagiota", "Konstantina", "Anastasia", "Georgia", "Eleni", "Stavroula", "Eirini", "Eleni", "Eleftheria", "Marina", "Kalliopi", "Argyro", "Paraskevi", "Vasiliki", "Theodora", "Katerina", "Dimitra", "Aikaterini", "Vasiliki", "Dionysia", "Maria", "Eleni", "Sofia", "Chrysa", "Panagiota", "Dimitra", "Anastasia", "Zoi", "Eirini", "Nikoleta", "Chrysoula", "Styliani", "Ioanna", "Maria", "Efi", "Eleni", "Maria", "Georgia", "Zeta", "Olga", "Aspasia", "Georgia", "Kalliopi", "Maria", "Katerina", "Niki", "Katerina", "Eleftheria", "Iro", "Chrysa", "Stavroula", "Eirini", "Christina", "Paraskevi", "Angeliki", "Vasiliki", "Katerina", "Panagiota", "Katerina", "Dimitra", "Alexandra", "Maria", "Katerina", "Nikoleta", "Anna", "Eleni", "Dimitra", "Anastasia", "Efi", "Aggeliki", "Katerina", "Stavroula", "Vasiliki", "Ioanna"],
      last_names: ["Papadopoulos", "Papadakis", "Nikolaidis", "Vlachos", "Katsouras", "Kapetanakis", "Kalogeropoulos", "Makris", "Papadimitriou", "Papanikolaou", "Pantelidis", "Antoniou", "Konstantinou", "Samaras", "Georgiou", "Papageorgiou", "Papakonstantinou", "Papathanasiou", "Dimitriou", "Theodorou", "Papoutsis", "Ioannidis", "Karakostas", "Karagiannis", "Galanis", "Papazoglou", "Kontos", "Papandreou", "Tsiolis", "Matsoukas", "Papavasileiou", "Papoulidis", "Tzanakis", "Anastasiadis", "Konstantinidis", "Pavlou", "Mitsopoulos", "Alexopoulos", "Tsiakiris", "Efstathiou", "Mitsos", "Papageorgiou", "Konstantopoulos", "Kalogeris", "Papazisis", "Apostolopoulos", "Koutroumbas", "Papaloukas", "Karvounis", "Papadellis", "Stavropoulos", "Diamantopoulos", "Angelidis", "Papathanasis", "Papandreopoulos", "Kakouris", "Stamoulis", "Papanastasiou", "Papanikolopoulos", "Papafotis", "Papazachariou", "Tsalikis", "Papakostas", "Papazisis", "Tselios", "Papamichalis", "Papakonstantinidis", "Kanellopoulos", "Papageorgiou", "Kapetanios", "Tsilis", "Koukoulis", "Tsirigotis", "Papazisis", "Papafotis", "Papadakis", "Papaioannou", "Koutsoukos", "Papanikolaou", "Papoutsakis", "Papazoglou", "Kakouris", "Papoutsis", "Papavasileiou", "Papoulidis", "Tsalikis", "Papakostas", "Papazisis", "Tselios", "Papamichalis", "Papakonstantinidis", "Kanellopoulos", "Papageorgiou", "Kapetanios", "Tsilis", "Koukoulis", "Tsirigotis"]
    },
  
    chile: {
      male: ["Mateo", "Sebastián", "Martín", "Benjamín", "Lucas", "Nicolás", "Matías", "Joaquín", "Gabriel", "Ignacio", "Santiago", "Diego", "Tomás", "Felipe", "Ángel", "Pablo", "Maximiliano", "Emilio", "Daniel", "Alexander", "Vicente", "Bastian", "Eduardo", "Cristóbal", "Francisco", "Adrián", "Alejandro", "Rafael", "Fernando", "Renato", "Javier", "Miguel", "Andrés", "Hugo", "Leandro", "Carlos", "Lautaro", "Raúl", "Ricardo", "Pedro", "Feliciano", "Gonzalo", "Osvaldo", "Ariel", "Gustavo", "Raimundo", "César", "Esteban", "Felix", "Juan Carlos", "Rodrigo", "Hernán", "Edgar", "Manuel", "Patricio", "Rodolfo", "Víctor", "Claudio", "Armando", "Álvaro", "Lorenzo", "Leonardo", "Marcos", "Marco Antonio", "Jorge", "Braulio", "Baldomero", "Isidro", "Ernesto", "Ramiro", "Arturo", "Antonio", "Salvador", "Roberto", "Jaime", "Nelson", "René", "Fabián", "Bryan", "Cristian", "Eugenio", "Raul", "José", "Mauricio", "Elias", "Fidel", "Mario", "Vladimir", "Julio", "Gilberto", "Walter", "Néstor"],
      female: ["Isabella", "Sofía", "Valentina", "Emilia", "Martina", "Antonia", "Catalina", "Josefa", "Florencia", "Trinidad", "Fernanda", "Camila", "Renata", "Victoria", "Amanda", "Emma", "Javiera", "Constanza", "Agustina", "Gabriela", "Maite", "Rocío", "Paula", "Emiliana", "Luz", "Aurora", "Belen", "María José", "Isidora", "Carmen", "Sara", "Mía", "Cecilia", "Valerie", "Rafaela", "Rosa", "Amelia", "Isabel", "Laura", "Daniela", "Francisca", "Carolina", "Mariana", "Clara", "Paz", "Lucía", "Alejandra", "Pía", "Julia", "Isidora", "Luna", "Ivanna", "Elena", "Bárbara", "Valeria", "Josefina", "Gabriela", "Vanessa", "Margarita", "Beatriz", "Adela", "Nicole", "Violeta", "Alicia", "Gloria", "Irma", "Yasna", "Ester", "Patricia", "Eugenia", "Araceli", "Silvana", "Julieta", "Lorena", "Mónica", "Liliana", "Rita", "Diana", "Angélica", "Rosario", "Teresa", "Leticia", "Natalia", "Claudia", "Laura", "Paola", "Verónica", "Susana", "Rocío", "Inés"],
      last_names: ["González", "Rodríguez", "Gómez", "Fernández", "López", "Díaz", "Pérez", "Torres", "Vargas", "Rojas", "Soto", "Contreras", "Silva", "Morales", "Carrasco", "Castro", "Sepúlveda", "Valenzuela", "Araya", "Martínez", "Álvarez", "Reyes", "Ramírez", "Flores", "Navarro", "Henríquez", "Espinoza", "Muñoz", "Jara", "Cordero", "Molina", "Méndez", "Vega", "Aguilera", "Pizarro", "Herrera", "Cabrera", "Campos", "Ríos", "Ortiz", "Tapia", "Jiménez", "Sanchez", "Parra", "Leiva", "Castillo", "Cisternas", "Ortega", "Bravo", "Araneda", "Arias", "Godoy", "Sandoval", "Navarrete", "Medina", "Cáceres", "Santander", "Villanueva", "Collao", "Cárcamo", "Lara", "Salgado", "Fuentes", "Castellón", "Cisternas", "Romero", "Barraza", "Garrido", "Ulloa", "Palma", "Catalán", "Orellana", "Avila", "Moreno", "Figueroa", "Montenegro", "Gallardo", "Quezada", "Riquelme", "Carvajal", "Villalobos", "Ahumada", "Yáñez", "Sáez", "Zamorano", "Vera"]
    }
  };

  const generatedNames = [];
  for (let i = 0; i < count; i++) {
    let selectedCountry = country; // New: Use the specified country

    // If no country is specified or the specified country does not exist, choose one randomly
    if (!names[selectedCountry]) {
      const matchingCountries = Object.keys(names).filter((country) => {
        const { male, female, last_names } = names[country];
        const namesArray = [
          ...male,
          ...female,
          ...(mergedSettings.generate_last_name ? last_names : []),
        ];
        return namesArray.some((name) => {
          const firstName = name.split(' ')[0];
          return (
            (starts_with === 'any' || firstName.startsWith(starts_with)) &&
            (ends_with === 'any' || firstName.endsWith(ends_with))
          );
        });
      });

      selectedCountry =
        matchingCountries.length > 0 ? getRandomElement(matchingCountries) : 'denmark';
    }

    let firstName = '';
    let lastName = '';

    if (gender === 'male') {
      const filteredMaleNames = filterNames(
        names[selectedCountry].male,
        starts_with,
        ends_with
      );
      firstName = getRandomElement(filteredMaleNames);
    } else if (gender === 'female') {
      const filteredFemaleNames = filterNames(
        names[selectedCountry].female,
        starts_with,
        ends_with
      );
      firstName = getRandomElement(filteredFemaleNames);
    } else {
      const allMaleNames = filterNames(
        names[selectedCountry].male,
        starts_with,
        ends_with
      );
      const allFemaleNames = filterNames(
        names[selectedCountry].female,
        starts_with,
        ends_with
      );
      const allNames = [...allMaleNames, ...allFemaleNames];
      firstName = getRandomElement(allNames);
    }

    if (mergedSettings.generate_last_name) {
      lastName = getRandomElement(names[selectedCountry].last_names);
    }

    const fullName = `${title} ${firstName} ${lastName}`.trim();

    if (names_with_title > 0) {
      const numNamesWithTitle = Math.round(
        (names_with_title / 100) * count
      );

      if (i < numNamesWithTitle) {
        generatedNames.push(fullName);
      } else {
        generatedNames.push(`${firstName} ${lastName}`);
      }
    } else {
      generatedNames.push(`${firstName} ${lastName}`);
    }
  }

  return generatedNames;
}